@extends('layouts.app')
@section('title','Dashboard')
@section('content')
<section class="hero"><div><span class="eyebrow">Willkommen zurück</span><h1>Deine Aufträge im Blick.</h1><p>Heute siehst du sofort, welche Nachweise noch offen sind und welche Vergütung bereits vorgemerkt wurde.</p><a class="btn primary" href="{{ route('offers.index') }}">Neue Angebote ansehen</a></div><div class="hero-stats"><div><span>Vorgemerkt</span><strong>{{ number_format($wallet->balance('pending'),2,',','.') }} €</strong></div><div><span>Verfügbar</span><strong>{{ number_format($wallet->balance('available'),2,',','.') }} €</strong></div></div></section>
<div class="dashboard-grid"><section><div class="section-head"><div><span class="eyebrow">Heute</span><h2>Laufende Aufträge</h2></div><a href="{{ route('orders.index') }}">Alle anzeigen →</a></div>
<div class="cards two">@forelse($activeOrders as $order)<a class="task-card" href="{{ route('orders.show',$order) }}"><div><span class="status {{ $order->status }}">{{ strtoupper(str_replace('_',' ',$order->status)) }}</span><h3>#{{ $order->order_number }} · {{ data_get($order->offer_snapshot,'title') }}</h3><p>{{ $order->start_date ? 'Tag '.max(1,today()->diffInDays($order->start_date,false)+1).' von '.data_get($order->offer_snapshot,'duration_days') : 'Noch nicht gestartet' }}</p></div><strong>{{ number_format($order->compensation_total,2,',','.') }} €</strong></a>@empty<div class="empty">Noch kein laufender Auftrag. Wähle ein Angebot aus und starte deinen ersten Auftrag.</div>@endforelse</div></section>
<aside class="wallet-card"><span class="eyebrow">Dein Wallet</span><h2>{{ number_format($wallet->balance('available'),2,',','.') }} €</h2><dl><div><dt>Vorgemerkt</dt><dd>{{ number_format($wallet->balance('pending'),2,',','.') }} €</dd></div><div><dt>Verfügbar</dt><dd>{{ number_format($wallet->balance('available'),2,',','.') }} €</dd></div></dl><a class="btn primary wide" href="{{ route('wallet.index') }}">Zum Wallet</a></aside></div>
<section><div class="section-head"><div><span class="eyebrow">Neu</span><h2>Aktuelle Angebote</h2></div><a href="{{ route('offers.index') }}">Alle Angebote →</a></div><div class="offer-grid">@foreach($offers as $offer)@include('components.offer-card',['offer'=>$offer])@endforeach</div></section>
@endsection
