@extends('layouts.app')
@section('title',$offer->exists?'Angebot bearbeiten':'Neues Angebot')
@section('content')
<div class="page-head"><span class="eyebrow">Angebotseditor</span><h1>{{ $offer->exists?'Angebot bearbeiten':'Neues Angebot erstellen' }}</h1><p>V1: Kategorie, Vergütung, Erfüllungslogik, Nachweise und Optionen. Änderungen erzeugen automatisch eine neue Angebotsversion.</p></div>
<form method="post" action="{{ $offer->exists?route('admin.offers.update',$offer):route('admin.offers.store') }}" class="editor-grid" data-option-editor>@csrf @if($offer->exists)@method('PUT')@endif
<section class="panel"><h2>Grunddaten</h2><div class="form-grid">
<label>Titel<input name="title" value="{{ old('title',$offer->title) }}" required></label>
<label>Kategorie<select name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$offer->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></label>
<label class="full">Kurzbeschreibung<input name="short_description" value="{{ old('short_description',$offer->short_description) }}"></label>
<label class="full">Beschreibung<textarea name="description" rows="6">{{ old('description',$offer->description) }}</textarea></label>
<label>Grundvergütung (€)<input type="number" step="0.01" min="0" name="base_compensation" value="{{ old('base_compensation',$offer->base_compensation??40) }}" required></label>
<label>Dauer / Grundumfang in Tagen<input type="number" min="1" name="duration_days" value="{{ old('duration_days',$offer->duration_days??1) }}" required></label>
<label>Erfüllungstyp<select name="fulfillment_type"><option value="days" @selected(old('fulfillment_type',$offer->fulfillment_type)==='days')>Tage / Tragezeit</option><option value="units" @selected(old('fulfillment_type',$offer->fulfillment_type)==='units')>Einheiten / Menge</option><option value="one_time" @selected(old('fulfillment_type',$offer->fulfillment_type)==='one_time')>Einmalige Leistung</option><option value="digital" @selected(old('fulfillment_type',$offer->fulfillment_type)==='digital')>Digitale Leistung</option><option value="combination" @selected(old('fulfillment_type',$offer->fulfillment_type)==='combination')>Kombination</option></select></label>
<label>Status<select name="lifecycle_status"><option value="draft" @selected(old('lifecycle_status',$offer->lifecycle_status??'draft')==='draft')>Entwurf</option><option value="active" @selected(old('lifecycle_status',$offer->lifecycle_status)==='active')>Aktiv</option><option value="deactivated" @selected(old('lifecycle_status',$offer->lifecycle_status)==='deactivated')>Deaktiviert</option></select></label>
<label>Tracking im Versand<select name="tracking_mode"><option value="required" @selected(old('tracking_mode',$offer->tracking_mode)==='required')>Pflicht</option><option value="optional" @selected(old('tracking_mode',$offer->tracking_mode??'optional')==='optional')>Optional</option><option value="none" @selected(old('tracking_mode',$offer->tracking_mode)==='none')>Nicht vorgesehen</option></select></label>
<label class="full">Regeln – eine pro Zeile<textarea name="rules_text" rows="6">{{ old('rules_text',is_array($offer->rules)?implode("\n",$offer->rules):'') }}</textarea></label>
</div><div class="notice">Physische Kategorien erhalten automatisch eine Vorabkontrolle. Angebote haben keine Kapazitätsgrenze und bleiben aktiv, bis du sie deaktivierst.</div></section>

<section class="panel" data-proof-window-editor><div class="section-head"><div><span class="eyebrow">Nachweise</span><h2>Reguläre Zeitfenster</h2></div><button type="button" class="btn secondary" data-add-proof-window>+ Zeitfenster</button></div>
<p class="muted">Standard: morgens 06:00–10:00, mittags 12:00–16:00, abends 18:00–23:59. Bei digitalen Angeboten können die Fenster entfernt werden.</p><div data-proof-windows>
@foreach(old('proof_windows',$proofRows) as $i=>$window)<div class="option-editor-row">
<label>Schlüssel<input name="proof_windows[{{ $i }}][key]" value="{{ $window['key']??'' }}"></label><label>Bezeichnung<input name="proof_windows[{{ $i }}][label]" value="{{ $window['label']??'' }}"></label><label>Von<input type="time" name="proof_windows[{{ $i }}][start]" value="{{ $window['start']??'06:00' }}"></label><label>Bis<input type="time" name="proof_windows[{{ $i }}][end]" value="{{ $window['end']??'10:00' }}"></label><label>Bilder<input type="number" min="1" max="20" name="proof_windows[{{ $i }}][required_images]" value="{{ $window['required_images']??1 }}"></label><label class="check"><input type="checkbox" name="proof_windows[{{ $i }}][text_required]" value="1" @checked($window['text_required']??false)><span>Text</span></label><label class="check"><input type="checkbox" name="proof_windows[{{ $i }}][face_required]" value="1" @checked($window['face_required']??false)><span>Gesicht erforderlich</span></label><label class="wide">Bildanforderungen<textarea name="proof_windows[{{ $i }}][image_requirements]" rows="2">{{ $window['image_requirements']??'' }}</textarea></label><label class="wide">Zusätzliche Pflichtangaben – eine pro Zeile<textarea name="proof_windows[{{ $i }}][required_fields_text]" rows="3">{{ $window['required_fields_text']??'' }}</textarea></label><button type="button" class="icon-btn" data-remove-proof-window>×</button>
</div>@endforeach</div></section>

<section class="panel"><div class="section-head"><div><span class="eyebrow">Optionen</span><h2>Zusatzoptionen</h2></div><button type="button" class="btn secondary" data-add-option>+ Option</button></div><div data-options>
@foreach(old('options',$optionRows) as $i=>$option)<div class="option-editor-row" style="grid-template-columns:1.1fr .7fr .7fr .7fr .7fr 1.1fr 1.1fr auto"><input type="hidden" name="options[{{ $i }}][id]" value="{{ $option['id']??'' }}"><label>Name<input name="options[{{ $i }}][name]" value="{{ $option['name']??'' }}"></label><label>Aufpreis (€)<input type="number" step="0.01" min="0" name="options[{{ $i }}][price_delta]" value="{{ $option['price_delta']??0 }}"></label><label>Extra-Nachweise/Tag<input type="number" min="0" name="options[{{ $i }}][extra_proofs_per_day]" value="{{ $option['extra_proofs_per_day']??0 }}"></label><label>Extra-Tage<input type="number" min="0" name="options[{{ $i }}][extra_duration_days]" value="{{ $option['extra_duration_days']??0 }}"></label><label>Mindestlaufzeit<input type="number" min="0" name="options[{{ $i }}][min_duration_days]" value="{{ $option['min_duration_days']??0 }}"></label><label>Benötigt Optionen<input name="options[{{ $i }}][requires_names]" value="{{ $option['requires_names']??'' }}"></label><label>Schließt aus<input name="options[{{ $i }}][excludes_names]" value="{{ $option['excludes_names']??'' }}"></label><label class="check"><input type="checkbox" name="options[{{ $i }}][required]" value="1" @checked($option['required']??false)><span>Pflicht</span></label><label class="wide" style="grid-column:1/-2">Beschreibung<input name="options[{{ $i }}][description]" value="{{ $option['description']??'' }}"></label><button type="button" class="icon-btn" data-remove-option>×</button></div>@endforeach
</div></section>

<section class="panel" data-field-editor><div class="section-head"><div><span class="eyebrow">Felder</span><h2>Auftragsspezifische Angaben</h2></div><button type="button" class="btn secondary" data-add-field>+ Feld</button></div><div data-fields>
@foreach(old('fields',$fieldRows) as $i=>$field)<div class="option-editor-row"><input type="hidden" name="fields[{{ $i }}][id]" value="{{ $field['id']??'' }}"><label>Bezeichnung<input name="fields[{{ $i }}][label]" value="{{ $field['label']??'' }}"></label><label>Typ<select name="fields[{{ $i }}][type]">@foreach(['text'=>'Text','textarea'=>'Textbereich','number'=>'Zahl','select'=>'Auswahl','radio'=>'Radio','checkbox'=>'Ja/Nein','date'=>'Datum','multiselect'=>'Mehrfachauswahl'] as $type=>$label)<option value="{{ $type }}" @selected(($field['type']??'text')===$type)>{{ $label }}</option>@endforeach</select></label><label class="wide">Hilfetext<input name="fields[{{ $i }}][help_text]" value="{{ $field['help_text']??'' }}"></label><label class="wide">Auswahlwerte – eine pro Zeile<textarea name="fields[{{ $i }}][options_text]" rows="3">{{ $field['options_text']??'' }}</textarea></label><label class="check"><input type="checkbox" name="fields[{{ $i }}][required]" value="1" @checked($field['required']??false)><span>Pflichtfeld</span></label><button type="button" class="icon-btn" data-remove-field>×</button></div>@endforeach
</div></section>
<div class="editor-actions"><button class="btn primary">Angebot speichern</button></div></form>
@endsection
