<?php
declare(strict_types=1);
require __DIR__.'/app/Core.php';

$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH) ?: '/';
$base=parse_url((string)app_config('app.url',''),PHP_URL_PATH) ?: '';
if($base && $base!=='/' && str_starts_with($path,$base)) $path=substr($path,strlen($base)) ?: '/';
$method=$_SERVER['REQUEST_METHOD']??'GET';
if($method==='POST') csrf_verify();

function status_badge(string $status,string $label): string { return '<span class="status status-'.e($status).'">'.e($label).'</span>'; }
function offer_or_404(int $id): array { $q=db()->prepare("SELECT o.*,CONCAT(s.first_name,' ',s.last_name) seller_name,s.email seller_email FROM offers o JOIN sellers s ON s.id=o.seller_id WHERE o.id=?");$q->execute([$id]);$o=$q->fetch();if(!$o)not_found();return $o; }
function seller_offer_or_404(int $id,int $sellerId): array { $q=db()->prepare('SELECT * FROM offers WHERE id=? AND seller_id=?');$q->execute([$id,$sellerId]);$o=$q->fetch();if(!$o)not_found();return $o; }
function order_or_404(int $id): array { $q=db()->prepare("SELECT o.*,p.position_no,p.title position_title,CONCAT(s.first_name,' ',s.last_name) seller_name FROM orders o JOIN offer_positions p ON p.id=o.position_id JOIN sellers s ON s.id=o.seller_id WHERE o.id=?");$q->execute([$id]);$o=$q->fetch();if(!$o)not_found();return $o; }
function seller_order_or_404(int $id,int $sellerId): array { $q=db()->prepare("SELECT o.*,p.position_no,p.title position_title FROM orders o JOIN offer_positions p ON p.id=o.position_id WHERE o.id=? AND o.seller_id=?");$q->execute([$id,$sellerId]);$o=$q->fetch();if(!$o)not_found();return $o; }
function stream_private_image(string $table,int $id): never {
    $meta=$table==='precheck_uploads'
      ? ["join"=>"precheck_uploads u JOIN orders o ON o.id=u.order_id","seller"=>"o.seller_id"]
      : ["join"=>"day_uploads u JOIN order_days d ON d.id=u.day_id JOIN orders o ON o.id=d.order_id","seller"=>"o.seller_id"];
    $q=db()->prepare("SELECT u.*,{$meta['seller']} owner_id FROM {$meta['join']} WHERE u.id=?");$q->execute([$id]);$f=$q->fetch();if(!$f)not_found();
    $u=current_user();$allowed=$u && ($u['role']==='admin'||($u['role']==='seller'&&(int)$u['id']===(int)$f['owner_id']));
    if(!$allowed){http_response_code(403);exit('Zugriff verweigert.');}
    $rel=ltrim((string)$f['file_path'],'/');if($rel===''||str_contains($rel,'..')||str_contains($rel,"\0"))not_found();$real=__DIR__.'/storage/private/'.$rel;if(!is_file($real))not_found();
    header('Content-Type: '.(string)$f['mime_type']);header('Content-Length: '.filesize($real));header('Cache-Control: private, no-store');readfile($real);exit;
}

if(preg_match('#^/file/(precheck|day)/(\d+)$#',$path,$m)&&$method==='GET') stream_private_image($m[1]==='precheck'?'precheck_uploads':'day_uploads',(int)$m[2]);

if($path==='/'&&$method==='GET'){ $u=current_user(); if(!$u)redirect('/login'); redirect($u['role']==='admin'?'/admin':'/seller'); }

if($path==='/login'&&$method==='GET'){
    if(current_user()) redirect('/');
    ob_start();?><div class="auth-shell"><section class="auth-copy"><div class="eyebrow">Privates Auftragsportal</div><h1>Ein klarer Ablauf. Keine Shop-Komplexität.</h1><p>Direktangebote, positionsbezogene Vorabkontrollen und tägliche Foto-Nachweise in einem schlanken System.</p><div class="feature-list"><span>✓ 2 Rollen: Admin/Käufer und Verkäuferin</span><span>✓ Jede Position wird ein eigener Auftrag</span><span>✓ Nicht erfüllt = automatisch +1 Durchführungstag</span></div></section><form class="panel auth-card" method="post"><?=csrf_field()?><h2>Anmelden</h2><label>E-Mail<input type="email" name="email" required autofocus></label><label>Passwort<input type="password" name="password" required></label><button class="btn full">Anmelden</button></form></div><?php render('Anmelden',ob_get_clean());exit;
}
if($path==='/login'&&$method==='POST'){
    $email=strtolower(post('email'));$password=(string)($_POST['password']??'');
    $q=db()->prepare('SELECT id,password_hash FROM admins WHERE email=?');$q->execute([$email]);$row=$q->fetch();$role='admin';
    if(!$row){$q=db()->prepare('SELECT id,password_hash,active FROM sellers WHERE email=?');$q->execute([$email]);$row=$q->fetch();$role='seller';if($row && !(int)$row['active'])$row=false;}
    if(!$row||!password_verify($password,(string)$row['password_hash'])){flash('error','E-Mail oder Passwort ist falsch.');redirect('/login');}
    session_regenerate_id(true);$_SESSION['role']=$role;$_SESSION['user_id']=(int)$row['id'];redirect('/');
}
if($path==='/logout'&&$method==='GET'){$_SESSION=[];if(session_status()===PHP_SESSION_ACTIVE)session_destroy();redirect('/login');}

// ADMIN DASHBOARD
if($path==='/admin'&&$method==='GET'){
    require_admin();
    $stats=[
      'sent'=>(int)db()->query("SELECT COUNT(*) FROM offers WHERE status='sent'")->fetchColumn(),
      'precheck'=>(int)db()->query("SELECT COUNT(*) FROM orders WHERE status='precheck'")->fetchColumn(),
      'review'=>(int)db()->query("SELECT COUNT(*) FROM order_days WHERE status='submitted'")->fetchColumn(),
      'running'=>(int)db()->query("SELECT COUNT(*) FROM orders WHERE status='running'")->fetchColumn(),
    ];
    $recent=db()->query("SELECT o.id,o.offer_no,o.title,o.status,CONCAT(s.first_name,' ',s.last_name) seller_name FROM offers o JOIN sellers s ON s.id=o.seller_id ORDER BY o.created_at DESC LIMIT 8")->fetchAll();
    ob_start();?><div class="page-head"><div><div class="eyebrow">Admin / Käufer</div><h1>Übersicht</h1><p>Alles Wichtige für Angebote, Vorabkontrollen und Tagesprüfungen.</p></div><a class="btn" href="<?=e(url('/admin/offers/new'))?>">+ Neues Angebot</a></div>
    <div class="stats"><div class="stat"><span>Offene Angebote</span><strong><?=$stats['sent']?></strong></div><div class="stat"><span>Vorabkontrollen</span><strong><?=$stats['precheck']?></strong></div><div class="stat"><span>Tage zu prüfen</span><strong><?=$stats['review']?></strong></div><div class="stat"><span>Laufende Aufträge</span><strong><?=$stats['running']?></strong></div></div>
    <section class="panel"><div class="section-head"><h2>Letzte Angebote</h2><a href="<?=e(url('/admin/offers'))?>">Alle ansehen</a></div><div class="list"><?php foreach($recent as $o):?><a class="list-row" href="<?=e(url('/admin/offers/'.$o['id']))?>"><div><strong><?=e($o['offer_no'].' · '.$o['title'])?></strong><span><?=e($o['seller_name'])?></span></div><?=status_badge((string)$o['status'],offer_status_label((string)$o['status']))?></a><?php endforeach;?><?php if(!$recent):?><div class="empty">Noch keine Angebote.</div><?php endif;?></div></section><?php render('Admin',ob_get_clean());exit;
}

// SELLERS
if($path==='/admin/sellers'&&$method==='GET'){
    require_admin();$rows=db()->query("SELECT s.*,(SELECT COUNT(*) FROM offers o WHERE o.seller_id=s.id) offer_count FROM sellers s ORDER BY s.first_name,s.last_name")->fetchAll();
    ob_start();?><div class="page-head"><div><div class="eyebrow">Verkäuferinnen</div><h1>Konten</h1></div><a class="btn" href="<?=e(url('/admin/sellers/new'))?>">+ Verkäuferin</a></div><div class="cards"><?php foreach($rows as $s):?><article class="card"><div class="card-top"><span class="badge"><?=((int)$s['active'])?'Aktiv':'Deaktiviert'?></span><span class="muted"><?=e($s['offer_count'])?> Angebot(e)</span></div><h3><?=e($s['first_name'].' '.$s['last_name'])?></h3><p class="muted"><?=e($s['email'])?></p></article><?php endforeach;?><?php if(!$rows):?><div class="empty">Noch keine Verkäuferin angelegt.</div><?php endif;?></div><?php render('Verkäuferinnen',ob_get_clean());exit;
}
if($path==='/admin/sellers/new'&&$method==='GET'){
    require_admin();ob_start();?><div class="page-head"><div><div class="eyebrow">Neues Konto</div><h1>Verkäuferin anlegen</h1></div></div><form class="panel narrow" method="post"><?=csrf_field()?><div class="form-grid"><label>Vorname<input name="first_name" required></label><label>Nachname<input name="last_name" required></label></div><label>E-Mail<input type="email" name="email" required></label><label>Startpasswort<input type="password" name="password" minlength="10" required></label><button class="btn">Konto anlegen</button></form><?php render('Verkäuferin anlegen',ob_get_clean());exit;
}
if($path==='/admin/sellers/new'&&$method==='POST'){
    require_admin();$email=strtolower(post('email'));$pass=(string)($_POST['password']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($pass)<10||!post('first_name')||!post('last_name')){flash('error','Bitte alle Felder korrekt ausfüllen.');redirect('/admin/sellers/new');}
    try{db()->prepare('INSERT INTO sellers(email,first_name,last_name,password_hash) VALUES(?,?,?,?)')->execute([$email,post('first_name'),post('last_name'),password_hash($pass,PASSWORD_DEFAULT)]);}catch(Throwable){flash('error','Die E-Mail ist bereits vergeben.');redirect('/admin/sellers/new');}
    flash('success','Verkäuferin wurde angelegt.');redirect('/admin/sellers');
}

// ADMIN OFFERS
if($path==='/admin/offers'&&$method==='GET'){
    require_admin();$rows=db()->query("SELECT o.*,CONCAT(s.first_name,' ',s.last_name) seller_name,(SELECT COUNT(*) FROM offer_positions p WHERE p.offer_id=o.id) position_count FROM offers o JOIN sellers s ON s.id=o.seller_id ORDER BY o.created_at DESC")->fetchAll();
    ob_start();?><div class="page-head"><div><div class="eyebrow">Angebote</div><h1>Direktangebote</h1></div><a class="btn" href="<?=e(url('/admin/offers/new'))?>">+ Neues Angebot</a></div><div class="cards"><?php foreach($rows as $o):?><a class="card link-card" href="<?=e(url('/admin/offers/'.$o['id']))?>"><div class="card-top"><?=status_badge((string)$o['status'],offer_status_label((string)$o['status']))?><span class="muted"><?=e($o['position_count'])?> Position(en)</span></div><h3><?=e($o['offer_no'].' · '.$o['title'])?></h3><p><?=e($o['seller_name'])?></p></a><?php endforeach;?><?php if(!$rows):?><div class="empty">Noch keine Angebote.</div><?php endif;?></div><?php render('Angebote',ob_get_clean());exit;
}
if($path==='/admin/offers/new'&&$method==='GET'){
    require_admin();$sellers=db()->query("SELECT id,first_name,last_name,email FROM sellers WHERE active=1 ORDER BY first_name,last_name")->fetchAll();ob_start();?><div class="page-head"><div><div class="eyebrow">Neues Direktangebot</div><h1>Angebot erstellen</h1></div></div><form class="panel" method="post"><?=csrf_field()?><div class="form-grid"><label>Verkäuferin<select name="seller_id" required><option value="">Bitte wählen</option><?php foreach($sellers as $s):?><option value="<?=$s['id']?>"><?=e($s['first_name'].' '.$s['last_name'].' · '.$s['email'])?></option><?php endforeach;?></select></label><label>Titel<input name="title" required maxlength="190" placeholder="z. B. Socken + Schuhe"></label></div><label>Einleitung / Hinweise<textarea name="intro" rows="4"></textarea></label><label>Regeln, die bei Annahme verbindlich akzeptiert werden müssen<textarea name="rules_text" rows="10" required placeholder="Regeln des Gesamtangebots"></textarea></label><button class="btn">Entwurf erstellen</button></form><?php render('Angebot erstellen',ob_get_clean());exit;
}
if($path==='/admin/offers/new'&&$method==='POST'){
    $a=require_admin();$sellerId=(int)post('seller_id');$title=post('title');$rules=post('rules_text');if(!$sellerId||!$title||!$rules){flash('error','Verkäuferin, Titel und Regeln sind Pflicht.');redirect('/admin/offers/new');}
    $q=db()->prepare('SELECT COUNT(*) FROM sellers WHERE id=? AND active=1');$q->execute([$sellerId]);if((int)$q->fetchColumn()!==1){flash('error','Verkäuferin nicht gefunden.');redirect('/admin/offers/new');}
    $no=offer_number();db()->prepare("INSERT INTO offers(offer_no,seller_id,admin_id,title,intro,rules_text,status) VALUES(?,?,?,?,?,?,'draft')")->execute([$no,$sellerId,$a['id'],$title,post('intro')?:null,$rules]);$id=(int)db()->lastInsertId();log_event($id,null,'offer.created');redirect('/admin/offers/'.$id);
}
if(preg_match('#^/admin/offers/(\d+)$#',$path,$m)&&$method==='GET'){
    require_admin();$id=(int)$m[1];$o=offer_or_404($id);$q=db()->prepare('SELECT * FROM offer_positions WHERE offer_id=? ORDER BY position_no');$q->execute([$id]);$positions=$q->fetchAll();
    $q=db()->prepare("SELECT x.* FROM orders x WHERE x.offer_id=? ORDER BY x.order_no");$q->execute([$id]);$orders=$q->fetchAll();
    $q=db()->prepare('SELECT * FROM activity_log WHERE offer_id=? ORDER BY created_at DESC LIMIT 20');$q->execute([$id]);$events=$q->fetchAll();
    ob_start();?><div class="page-head"><div><div class="eyebrow">Angebot <?=e($o['offer_no'])?></div><h1><?=e($o['title'])?></h1><p><?=e($o['seller_name'].' · '.$o['seller_email'])?></p></div><?=status_badge((string)$o['status'],offer_status_label((string)$o['status']))?></div>
    <?php if($o['intro']):?><section class="panel"><h2>Hinweise</h2><p><?=nl2br(e($o['intro']))?></p></section><?php endif;?><section class="panel"><h2>Verbindliche Regeln</h2><p><?=nl2br(e($o['rules_text']))?></p></section>
    <div class="section-head"><h2>Positionen</h2></div><div class="cards"><?php foreach($positions as $p):?><article class="card"><div class="card-top"><span class="badge">Position <?=e($p['position_no'])?></span><strong><?=money($p['compensation'])?></strong></div><h3><?=e($p['title'])?></h3><p><?=nl2br(e($p['description']??''))?></p><div class="mini-grid"><span><b><?=e($p['required_success_days'])?></b> erfolgreiche Tage</span><span><b><?=e($p['precheck_photo_count'])?></b> Vorabfotos</span><span><b><?=e($p['daily_photo_count'])?></b> Fotos/Tag</span></div><p class="muted"><strong>Vorab:</strong> <?=e($p['precheck_instructions'])?><br><strong>Pro Tag:</strong> <?=e($p['daily_instructions'])?></p><?php if($o['status']==='draft'):?><form method="post" action="<?=e(url('/admin/offers/'.$id.'/positions/'.$p['id'].'/delete'))?>"><?=csrf_field()?><button class="btn ghost danger">Löschen</button></form><?php endif;?></article><?php endforeach;?><?php if(!$positions):?><div class="empty">Noch keine Positionen.</div><?php endif;?></div>
    <?php if($o['status']==='draft'):?><form class="panel" method="post" action="<?=e(url('/admin/offers/'.$id.'/positions'))?>"><h2>Position hinzufügen</h2><?=csrf_field()?><div class="form-grid"><label>Titel<input name="title" required></label><label>Vergütung (€)<input type="number" min="0" step="0.01" name="compensation" value="0.00" required></label><label>Erfolgreiche Tage<input type="number" min="1" max="365" name="required_success_days" value="1" required></label><label>Vorabfotos<input type="number" min="1" max="20" name="precheck_photo_count" value="1" required></label><label>Fotos pro Tag<input type="number" min="1" max="20" name="daily_photo_count" value="1" required></label></div><label>Beschreibung<textarea name="description" rows="3"></textarea></label><label>Anforderungen Vorabkontrolle<textarea name="precheck_instructions" rows="3" required></textarea></label><label>Anforderungen pro Durchführungstag<textarea name="daily_instructions" rows="3" required></textarea></label><button class="btn">Position hinzufügen</button></form><form class="panel action-panel" method="post" action="<?=e(url('/admin/offers/'.$id.'/send'))?>"><?=csrf_field()?><div><strong>Angebot fertig?</strong><p class="muted">Nach dem Senden bleiben die Positionen unverändert. Die Verkäuferin muss die Regeln zuerst akzeptieren.</p></div><button class="btn" <?=$positions?'':'disabled'?>>An Verkäuferin senden</button></form><?php endif;?>
    <?php if($orders):?><div class="section-head"><h2>Aufträge aus diesem Angebot</h2></div><?php foreach($orders as $ord): $full=order_or_404((int)$ord['id']); $pq=db()->prepare('SELECT * FROM precheck_uploads WHERE order_id=? ORDER BY id');$pq->execute([$ord['id']]);$pre=$pq->fetchAll(); $dq=db()->prepare('SELECT * FROM order_days WHERE order_id=? ORDER BY day_no');$dq->execute([$ord['id']]);$days=$dq->fetchAll();?><section class="panel"><div class="page-head"><div><div class="eyebrow">Position <?=e($full['position_no'])?></div><h2><?=e($full['order_no'].' · '.$full['position_title'])?></h2></div><?=status_badge((string)$full['status'],order_status_label((string)$full['status']))?></div><div class="stats compact"><div class="stat"><span>Erfolgreich</span><strong><?=e($full['successful_days'])?>/<?=e($full['required_success_days'])?></strong></div><div class="stat"><span>Verlängerung</span><strong>+<?=e($full['extension_days'])?></strong></div><div class="stat"><span>Vorab</span><strong><?=e(count($pre))?>/<?=e($full['precheck_photo_count'])?></strong></div></div>
    <?php if($pre):?><div class="photo-grid small"><?php foreach($pre as $f):?><a target="_blank" href="<?=e(url('/file/precheck/'.$f['id']))?>"><img src="<?=e(url('/file/precheck/'.$f['id']))?>" alt="Vorabfoto"></a><?php endforeach;?></div><?php endif;?>
    <?php if($full['status']==='precheck'):?><p><?=nl2br(e($full['precheck_instructions']))?></p><form method="post" action="<?=e(url('/admin/orders/'.$full['id'].'/approve-precheck'))?>"><?=csrf_field()?><button class="btn" <?=count($pre)<(int)$full['precheck_photo_count']?'disabled':''?>>Vorabkontrolle freigeben & starten</button></form><?php endif;?>
    <?php if($days):?><div class="day-list"><?php foreach($days as $d): $uq=db()->prepare('SELECT * FROM day_uploads WHERE day_id=? ORDER BY id');$uq->execute([$d['id']]);$ups=$uq->fetchAll();?><div class="day-row"><div class="day-main"><strong>Tag <?=e($d['day_no'])?></strong> <?=status_badge((string)$d['status'],day_status_label((string)$d['status']))?><?php if($d['is_extension']):?><span class="badge">Verlängerung</span><?php endif;?><p class="muted"><?=e(count($ups))?>/<?=e($d['required_photo_count'])?> Foto(s)<?= $d['seller_note']?' · '.$d['seller_note']:''?></p><?php if($ups):?><div class="photo-grid small"><?php foreach($ups as $f):?><a target="_blank" href="<?=e(url('/file/day/'.$f['id']))?>"><img src="<?=e(url('/file/day/'.$f['id']))?>" alt="Tagesfoto"></a><?php endforeach;?></div><?php endif;?></div><?php if($d['status']==='submitted'):?><form class="review-actions" method="post" action="<?=e(url('/admin/days/'.$d['id'].'/review'))?>"><?=csrf_field()?><textarea name="admin_note" rows="2" placeholder="Notiz optional"></textarea><div><button class="btn" name="decision" value="fulfilled">Erfüllt</button><button class="btn danger" name="decision" value="not_fulfilled">Nicht erfüllt (+1 Tag)</button></div></form><?php endif;?></div><?php endforeach;?></div><?php endif;?></section><?php endforeach;?><?php endif;?>
    <?php if($events):?><section class="panel"><h2>Verlauf</h2><div class="timeline"><?php foreach($events as $ev):?><div class="timeline-row"><span class="dot dot-<?=e(str_replace('.','_',str_contains($ev['event_type'],'not_fulfilled')?'not_fulfilled':(str_contains($ev['event_type'],'fulfilled')?'fulfilled':'submitted')))?>"></span><div><strong><?=e($ev['event_type'])?></strong><span><?=e(date('d.m.Y H:i',strtotime($ev['created_at'])))?></span></div></div><?php endforeach;?></div></section><?php endif;?><?php render('Angebot '.$o['offer_no'],ob_get_clean());exit;
}
if(preg_match('#^/admin/offers/(\d+)/positions$#',$path,$m)&&$method==='POST'){
    require_admin();$offerId=(int)$m[1];$o=offer_or_404($offerId);if($o['status']!=='draft'){flash('error','Nur Entwürfe können geändert werden.');redirect('/admin/offers/'.$offerId);} $title=post('title');if(!$title||!post('precheck_instructions')||!post('daily_instructions')){flash('error','Titel und Nachweisanweisungen sind Pflicht.');redirect('/admin/offers/'.$offerId);} $q=db()->prepare('SELECT COALESCE(MAX(position_no),0)+1 FROM offer_positions WHERE offer_id=?');$q->execute([$offerId]);$pos=(int)$q->fetchColumn();db()->prepare('INSERT INTO offer_positions(offer_id,position_no,title,description,compensation,required_success_days,precheck_photo_count,precheck_instructions,daily_photo_count,daily_instructions) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$offerId,$pos,$title,post('description')?:null,max(0,(float)post('compensation','0')),max(1,(int)post('required_success_days','1')),max(1,(int)post('precheck_photo_count','1')),post('precheck_instructions'),max(1,(int)post('daily_photo_count','1')),post('daily_instructions')]);log_event($offerId,null,'offer.position_added',['position_no'=>$pos]);flash('success','Position hinzugefügt.');redirect('/admin/offers/'.$offerId);
}
if(preg_match('#^/admin/offers/(\d+)/positions/(\d+)/delete$#',$path,$m)&&$method==='POST'){
    require_admin();$offerId=(int)$m[1];$o=offer_or_404($offerId);if($o['status']!=='draft'){flash('error','Nur Entwürfe können geändert werden.');redirect('/admin/offers/'.$offerId);}db()->prepare('DELETE FROM offer_positions WHERE id=? AND offer_id=?')->execute([(int)$m[2],$offerId]);$q=db()->prepare('SELECT id FROM offer_positions WHERE offer_id=? ORDER BY position_no,id');$q->execute([$offerId]);$n=1;foreach($q->fetchAll(PDO::FETCH_COLUMN) as $pid)db()->prepare('UPDATE offer_positions SET position_no=? WHERE id=?')->execute([$n++,$pid]);flash('success','Position gelöscht.');redirect('/admin/offers/'.$offerId);
}
if(preg_match('#^/admin/offers/(\d+)/send$#',$path,$m)&&$method==='POST'){
    require_admin();$id=(int)$m[1];$o=offer_or_404($id);$q=db()->prepare('SELECT COUNT(*) FROM offer_positions WHERE offer_id=?');$q->execute([$id]);if($o['status']!=='draft'||(int)$q->fetchColumn()<1){flash('error','Das Angebot muss ein Entwurf mit mindestens einer Position sein.');redirect('/admin/offers/'.$id);}db()->prepare("UPDATE offers SET status='sent',sent_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$id]);log_event($id,null,'offer.sent');flash('success','Angebot wurde freigeschaltet.');redirect('/admin/offers/'.$id);
}

if($path==='/admin/orders'&&$method==='GET'){
    require_admin();$rows=db()->query("SELECT o.*,p.position_no,CONCAT(s.first_name,' ',s.last_name) seller_name FROM orders o JOIN offer_positions p ON p.id=o.position_id JOIN sellers s ON s.id=o.seller_id ORDER BY FIELD(o.status,'precheck','running','completed','cancelled'),o.created_at DESC")->fetchAll();ob_start();?><div class="page-head"><div><div class="eyebrow">Aufträge</div><h1>Alle Positionen</h1></div></div><div class="list panel"><?php foreach($rows as $o):?><a class="list-row" href="<?=e(url('/admin/offers/'.$o['offer_id']))?>"><div><strong><?=e($o['order_no'].' · '.$o['title_snapshot'])?></strong><span><?=e($o['seller_name'])?> · <?=e($o['successful_days'])?>/<?=e($o['required_success_days'])?> erfolgreiche Tage · +<?=e($o['extension_days'])?></span></div><?=status_badge((string)$o['status'],order_status_label((string)$o['status']))?></a><?php endforeach;?><?php if(!$rows):?><div class="empty">Noch keine Aufträge.</div><?php endif;?></div><?php render('Aufträge',ob_get_clean());exit;
}
if(preg_match('#^/admin/orders/(\d+)/approve-precheck$#',$path,$m)&&$method==='POST'){
    require_admin();$id=(int)$m[1];$o=order_or_404($id);if($o['status']!=='precheck'){flash('error','Auftrag ist nicht in der Vorabkontrolle.');redirect('/admin/offers/'.$o['offer_id']);}$q=db()->prepare('SELECT COUNT(*) FROM precheck_uploads WHERE order_id=?');$q->execute([$id]);if((int)$q->fetchColumn()<(int)$o['precheck_photo_count']){flash('error','Es fehlen Vorabfotos.');redirect('/admin/offers/'.$o['offer_id']);}db()->beginTransaction();try{db()->prepare("UPDATE orders SET status='running',precheck_approved_at=NOW(),started_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$id]);$ins=db()->prepare("INSERT INTO order_days(order_id,day_no,is_extension,required_photo_count,status) VALUES(?,?,0,?,'planned')");for($n=1;$n<=(int)$o['required_success_days'];$n++)$ins->execute([$id,$n,$o['daily_photo_count']]);db()->commit();}catch(Throwable $e){db()->rollBack();throw $e;}log_event((int)$o['offer_id'],$id,'order.precheck_approved');sync_offer_status((int)$o['offer_id']);flash('success','Vorabkontrolle freigegeben. Auftrag läuft.');redirect('/admin/offers/'.$o['offer_id']);
}
if(preg_match('#^/admin/days/(\d+)/review$#',$path,$m)&&$method==='POST'){
    $a=require_admin();$dayId=(int)$m[1];$decision=post('decision');if(!in_array($decision,['fulfilled','not_fulfilled'],true)){flash('error','Ungültige Entscheidung.');redirect('/admin/orders');}$q=db()->prepare("SELECT d.*,o.offer_id,o.id order_id,o.required_success_days,o.daily_photo_count FROM order_days d JOIN orders o ON o.id=d.order_id WHERE d.id=?");$q->execute([$dayId]);$d=$q->fetch();if(!$d)not_found();if($d['status']!=='submitted'){flash('error','Nur eingereichte Tage können geprüft werden.');redirect('/admin/offers/'.$d['offer_id']);}
    db()->beginTransaction();try{db()->prepare('UPDATE order_days SET status=?,admin_note=?,reviewed_at=NOW(),reviewed_by=?,updated_at=NOW() WHERE id=?')->execute([$decision,post('admin_note')?:null,$a['id'],$dayId]);if($decision==='not_fulfilled'){$q=db()->prepare('SELECT COUNT(*) FROM order_days WHERE extension_for_day_id=?');$q->execute([$dayId]);if((int)$q->fetchColumn()===0){$q=db()->prepare('SELECT COALESCE(MAX(day_no),0)+1 FROM order_days WHERE order_id=?');$q->execute([$d['order_id']]);$next=(int)$q->fetchColumn();db()->prepare("INSERT INTO order_days(order_id,day_no,is_extension,extension_for_day_id,required_photo_count,status) VALUES(?,?,1,?,?,'planned')")->execute([$d['order_id'],$next,$dayId,$d['daily_photo_count']]);db()->prepare('UPDATE orders SET extension_days=extension_days+1,updated_at=NOW() WHERE id=?')->execute([$d['order_id']]);}}db()->commit();}catch(Throwable $e){db()->rollBack();throw $e;}log_event((int)$d['offer_id'],(int)$d['order_id'],'day.'.$decision,['day_no'=>(int)$d['day_no']]);sync_order_progress((int)$d['order_id']);flash('success',$decision==='fulfilled'?'Tag als erfüllt bestätigt.':'Tag als nicht erfüllt markiert. Ein zusätzlicher Durchführungstag wurde angehängt.');redirect('/admin/offers/'.$d['offer_id']);
}

// SELLER
if($path==='/seller'&&$method==='GET'){
    $s=require_seller();$q=db()->prepare("SELECT COUNT(*) FROM offers WHERE seller_id=? AND status='sent'");$q->execute([$s['id']]);$newOffers=(int)$q->fetchColumn();$q=db()->prepare("SELECT COUNT(*) FROM orders WHERE seller_id=? AND status='precheck'");$q->execute([$s['id']]);$pre=(int)$q->fetchColumn();$q=db()->prepare("SELECT COUNT(*) FROM orders WHERE seller_id=? AND status='running'");$q->execute([$s['id']]);$run=(int)$q->fetchColumn();$q=db()->prepare("SELECT o.*,p.position_no FROM orders o JOIN offer_positions p ON p.id=o.position_id WHERE o.seller_id=? ORDER BY o.created_at DESC LIMIT 6");$q->execute([$s['id']]);$orders=$q->fetchAll();ob_start();?><div class="page-head"><div><div class="eyebrow">Verkäuferin</div><h1>Hallo <?=e($s['first_name'])?></h1><p>Deine Angebote und aktuell offenen Nachweise.</p></div></div><div class="stats"><div class="stat"><span>Neue Angebote</span><strong><?=$newOffers?></strong></div><div class="stat"><span>Vorabkontrollen</span><strong><?=$pre?></strong></div><div class="stat"><span>Laufende Aufträge</span><strong><?=$run?></strong></div></div><section class="panel"><div class="section-head"><h2>Meine Aufträge</h2><a href="<?=e(url('/seller/orders'))?>">Alle</a></div><div class="list"><?php foreach($orders as $o):?><a class="list-row" href="<?=e(url('/seller/orders/'.$o['id']))?>"><div><strong><?=e($o['order_no'].' · '.$o['title_snapshot'])?></strong><span><?=e($o['successful_days'])?>/<?=e($o['required_success_days'])?> erfolgreiche Tage · +<?=e($o['extension_days'])?> Verlängerung</span></div><?=status_badge((string)$o['status'],order_status_label((string)$o['status']))?></a><?php endforeach;?><?php if(!$orders):?><div class="empty">Noch keine Aufträge.</div><?php endif;?></div></section><?php render('Übersicht',ob_get_clean());exit;
}
if($path==='/seller/offers'&&$method==='GET'){
    $s=require_seller();$q=db()->prepare("SELECT o.*,(SELECT COUNT(*) FROM offer_positions p WHERE p.offer_id=o.id) position_count FROM offers o WHERE o.seller_id=? AND o.status<>'draft' ORDER BY o.created_at DESC");$q->execute([$s['id']]);$rows=$q->fetchAll();ob_start();?><div class="page-head"><div><div class="eyebrow">Angebote</div><h1>Meine Direktangebote</h1></div></div><div class="cards"><?php foreach($rows as $o):?><a class="card link-card" href="<?=e(url('/seller/offers/'.$o['id']))?>"><div class="card-top"><?=status_badge((string)$o['status'],offer_status_label((string)$o['status']))?><span class="muted"><?=e($o['position_count'])?> Position(en)</span></div><h3><?=e($o['offer_no'].' · '.$o['title'])?></h3></a><?php endforeach;?><?php if(!$rows):?><div class="empty">Keine Angebote vorhanden.</div><?php endif;?></div><?php render('Meine Angebote',ob_get_clean());exit;
}
if(preg_match('#^/seller/offers/(\d+)$#',$path,$m)&&$method==='GET'){
    $s=require_seller();$id=(int)$m[1];$o=seller_offer_or_404($id,(int)$s['id']);if($o['status']==='draft')not_found();$q=db()->prepare('SELECT * FROM offer_positions WHERE offer_id=? ORDER BY position_no');$q->execute([$id]);$positions=$q->fetchAll();ob_start();?><div class="page-head"><div><div class="eyebrow">Angebot <?=e($o['offer_no'])?></div><h1><?=e($o['title'])?></h1></div><?=status_badge((string)$o['status'],offer_status_label((string)$o['status']))?></div><?php if($o['intro']):?><section class="panel"><p><?=nl2br(e($o['intro']))?></p></section><?php endif;?><section class="panel"><h2>Verbindliche Regeln</h2><p><?=nl2br(e($o['rules_text']))?></p></section><div class="cards"><?php foreach($positions as $p):?><article class="card"><span class="badge">Position <?=e($p['position_no'])?></span><h3><?=e($p['title'])?></h3><p><?=nl2br(e($p['description']??''))?></p><strong class="price"><?=money($p['compensation'])?></strong><div class="mini-grid"><span><b><?=e($p['required_success_days'])?></b> erfolgreiche Tage</span><span><b><?=e($p['precheck_photo_count'])?></b> Vorabfotos</span><span><b><?=e($p['daily_photo_count'])?></b> Fotos/Tag</span></div><p class="muted"><strong>Vorab:</strong> <?=e($p['precheck_instructions'])?><br><strong>Pro Tag:</strong> <?=e($p['daily_instructions'])?></p></article><?php endforeach;?></div><?php if($o['status']==='sent'):?><form class="panel" method="post" action="<?=e(url('/seller/offers/'.$id.'/accept'))?>"><?=csrf_field()?><h2>Verbindlich annehmen</h2><label class="check"><input type="checkbox" name="accept_rules" value="1" required><span>Ich habe die Regeln und Anforderungen vollständig gelesen und akzeptiere sie. Mir ist bekannt: Jede Position wird ein eigener Auftrag. Jeder vom Admin als „Nicht erfüllt“ bewertete Durchführungstag erzeugt automatisch einen zusätzlichen Tag.</span></label><button class="btn">Angebot annehmen</button></form><?php endif;?><?php render('Angebot '.$o['offer_no'],ob_get_clean());exit;
}
if(preg_match('#^/seller/offers/(\d+)/accept$#',$path,$m)&&$method==='POST'){
    $s=require_seller();$id=(int)$m[1];if(post('accept_rules')!=='1'){flash('error','Die Regeln müssen akzeptiert werden.');redirect('/seller/offers/'.$id);}db()->beginTransaction();try{$q=db()->prepare('SELECT * FROM offers WHERE id=? AND seller_id=? FOR UPDATE');$q->execute([$id,$s['id']]);$o=$q->fetch();if(!$o||$o['status']!=='sent')throw new RuntimeException('Dieses Angebot kann nicht mehr angenommen werden.');$q=db()->prepare('SELECT * FROM offer_positions WHERE offer_id=? ORDER BY position_no');$q->execute([$id]);$positions=$q->fetchAll();if(!$positions)throw new RuntimeException('Das Angebot enthält keine Positionen.');db()->prepare("UPDATE offers SET status='accepted',accepted_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$id]);db()->prepare('INSERT INTO offer_acceptances(offer_id,seller_id,rules_snapshot,positions_snapshot) VALUES(?,?,?,?)')->execute([$id,$s['id'],$o['rules_text'],json_encode($positions,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);$ins=db()->prepare("INSERT INTO orders(order_no,offer_id,position_id,seller_id,title_snapshot,description_snapshot,compensation,required_success_days,precheck_photo_count,precheck_instructions,daily_photo_count,daily_instructions,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'precheck')");foreach($positions as $p)$ins->execute([$o['offer_no'].'-'.str_pad((string)$p['position_no'],2,'0',STR_PAD_LEFT),$id,$p['id'],$s['id'],$p['title'],$p['description'],$p['compensation'],$p['required_success_days'],$p['precheck_photo_count'],$p['precheck_instructions'],$p['daily_photo_count'],$p['daily_instructions']]);db()->commit();}catch(Throwable $e){db()->rollBack();flash('error',$e->getMessage());redirect('/seller/offers/'.$id);}log_event($id,null,'offer.accepted');flash('success','Angebot angenommen. Bitte jetzt die Vorabkontrollen je Position durchführen.');redirect('/seller/orders');
}
if($path==='/seller/orders'&&$method==='GET'){
    $s=require_seller();$q=db()->prepare('SELECT * FROM orders WHERE seller_id=? ORDER BY created_at DESC');$q->execute([$s['id']]);$rows=$q->fetchAll();ob_start();?><div class="page-head"><div><div class="eyebrow">Aufträge</div><h1>Meine Positionen</h1></div></div><div class="cards"><?php foreach($rows as $o):?><a class="card link-card" href="<?=e(url('/seller/orders/'.$o['id']))?>"><div class="card-top"><?=status_badge((string)$o['status'],order_status_label((string)$o['status']))?><span class="muted">+<?=e($o['extension_days'])?> Verlängerung</span></div><h3><?=e($o['order_no'].' · '.$o['title_snapshot'])?></h3><p><?=e($o['successful_days'])?>/<?=e($o['required_success_days'])?> erfolgreiche Tage</p></a><?php endforeach;?><?php if(!$rows):?><div class="empty">Noch keine Aufträge.</div><?php endif;?></div><?php render('Meine Aufträge',ob_get_clean());exit;
}
if(preg_match('#^/seller/orders/(\d+)$#',$path,$m)&&$method==='GET'){
    $s=require_seller();$id=(int)$m[1];$o=seller_order_or_404($id,(int)$s['id']);$q=db()->prepare('SELECT * FROM precheck_uploads WHERE order_id=? ORDER BY id');$q->execute([$id]);$pre=$q->fetchAll();$q=db()->prepare('SELECT * FROM order_days WHERE order_id=? ORDER BY day_no');$q->execute([$id]);$days=$q->fetchAll();$current=null;foreach($days as $d){if(in_array($d['status'],['planned','submitted'],true)){$current=$d;break;}}ob_start();?><div class="page-head"><div><div class="eyebrow">Auftrag <?=e($o['order_no'])?></div><h1><?=e($o['position_title'])?></h1></div><?=status_badge((string)$o['status'],order_status_label((string)$o['status']))?></div><div class="stats compact"><div class="stat"><span>Erfolgreich</span><strong><?=e($o['successful_days'])?>/<?=e($o['required_success_days'])?></strong></div><div class="stat"><span>Verlängerung</span><strong>+<?=e($o['extension_days'])?></strong></div><div class="stat"><span>Vergütung</span><strong><?=money($o['compensation'])?></strong></div></div>
    <?php if($o['status']==='precheck'):?><section class="panel"><h2>Vorabkontrolle</h2><p><?=nl2br(e($o['precheck_instructions']))?></p><p class="muted"><?=e(count($pre))?>/<?=e($o['precheck_photo_count'])?> Foto(s) hochgeladen.</p><?php if($pre):?><div class="photo-grid"><?php foreach($pre as $f):?><a target="_blank" href="<?=e(url('/file/precheck/'.$f['id']))?>"><img src="<?=e(url('/file/precheck/'.$f['id']))?>" alt="Vorabfoto"></a><?php endforeach;?></div><?php endif;?><?php if(count($pre)<(int)$o['precheck_photo_count']):?><form method="post" enctype="multipart/form-data" action="<?=e(url('/seller/orders/'.$id.'/precheck'))?>"><?=csrf_field()?><label>Fehlende Vorabfotos<input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" capture="environment" multiple required></label><button class="btn">Hochladen</button></form><?php else:?><div class="notice success">Vorabkontrolle vollständig. Warte auf die Freigabe durch den Admin.</div><?php endif;?></section><?php endif;?>
    <?php if(in_array($o['status'],['running','completed'],true)):?><section class="panel"><h2>Durchführung</h2><p><?=nl2br(e($o['daily_instructions']))?></p><?php if($o['status']==='completed'):?><div class="notice success"><strong>Auftrag abgeschlossen.</strong> Alle <?=e($o['required_success_days'])?> erfolgreichen Tage wurden bestätigt.</div><?php elseif($current):?><div class="current-day"><div class="card-top"><h3>Tag <?=e($current['day_no'])?></h3><?php if($current['is_extension']):?><span class="badge">Verlängerung</span><?php endif;?></div><?php if($current['status']==='submitted'):?><p>Deine Fotos wurden eingereicht und warten auf die Prüfung des Admins.</p><?php else:?><p><?=e($current['required_photo_count'])?> Foto(s) erforderlich.</p><form method="post" enctype="multipart/form-data" action="<?=e(url('/seller/days/'.$current['id'].'/submit'))?>"><?=csrf_field()?><label>Fotos<input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" capture="environment" multiple required></label><label>Kommentar (optional)<textarea name="seller_note" rows="3"></textarea></label><button class="btn">Tag einreichen</button></form><?php endif;?></div><?php endif;?></section><section class="panel"><h2>Verlauf</h2><div class="timeline"><?php foreach($days as $d):?><div class="timeline-row"><span class="dot dot-<?=e($d['status'])?>"></span><div><strong>Tag <?=e($d['day_no'])?><?= $d['is_extension']?' · Verlängerung':''?></strong><span><?=e(day_status_label((string)$d['status']))?></span></div></div><?php endforeach;?></div></section><?php endif;?><?php render('Auftrag '.$o['order_no'],ob_get_clean());exit;
}
if(preg_match('#^/seller/orders/(\d+)/precheck$#',$path,$m)&&$method==='POST'){
    $s=require_seller();$id=(int)$m[1];$o=seller_order_or_404($id,(int)$s['id']);if($o['status']!=='precheck'){flash('error','Vorabkontrolle ist geschlossen.');redirect('/seller/orders/'.$id);}$q=db()->prepare('SELECT COUNT(*) FROM precheck_uploads WHERE order_id=?');$q->execute([$id]);$existing=(int)$q->fetchColumn();$needed=(int)$o['precheck_photo_count'];$files=normalized_uploads('photos');if(!$files){flash('error','Bitte mindestens ein Foto auswählen.');redirect('/seller/orders/'.$id);}if($existing+count($files)>$needed){flash('error','Bitte nur die noch fehlende Anzahl an Fotos hochladen.');redirect('/seller/orders/'.$id);}try{foreach($files as $f){$up=save_image_upload($f,'order-'.$id.'/precheck');db()->prepare('INSERT INTO precheck_uploads(order_id,seller_id,file_path,mime_type,file_size,sha256) VALUES(?,?,?,?,?,?)')->execute([$id,$s['id'],$up['path'],$up['mime'],$up['size'],$up['sha256']]);}log_event((int)$o['offer_id'],$id,'precheck.uploaded',['count'=>count($files)]);flash('success','Vorabfoto(s) gespeichert.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect('/seller/orders/'.$id);
}
if(preg_match('#^/seller/days/(\d+)/submit$#',$path,$m)&&$method==='POST'){
    $s=require_seller();$dayId=(int)$m[1];$q=db()->prepare("SELECT d.*,o.id order_id,o.offer_id,o.seller_id,o.status order_status FROM order_days d JOIN orders o ON o.id=d.order_id WHERE d.id=? AND o.seller_id=?");$q->execute([$dayId,$s['id']]);$d=$q->fetch();if(!$d)not_found();if($d['order_status']!=='running'||$d['status']!=='planned'){flash('error','Dieser Tag kann aktuell nicht eingereicht werden.');redirect('/seller/orders/'.$d['order_id']);}$q=db()->prepare("SELECT id FROM order_days WHERE order_id=? AND status IN('planned','submitted') ORDER BY day_no LIMIT 1");$q->execute([$d['order_id']]);if((int)$q->fetchColumn()!==$dayId){flash('error','Bitte die Durchführungstage der Reihe nach abschließen.');redirect('/seller/orders/'.$d['order_id']);}$files=normalized_uploads('photos');if(count($files)!==(int)$d['required_photo_count']){flash('error','Für diesen Tag sind genau '.$d['required_photo_count'].' Foto(s) erforderlich.');redirect('/seller/orders/'.$d['order_id']);}db()->beginTransaction();try{foreach($files as $f){$up=save_image_upload($f,'order-'.$d['order_id'].'/day-'.$d['day_no']);db()->prepare('INSERT INTO day_uploads(day_id,seller_id,file_path,mime_type,file_size,sha256) VALUES(?,?,?,?,?,?)')->execute([$dayId,$s['id'],$up['path'],$up['mime'],$up['size'],$up['sha256']]);}db()->prepare("UPDATE order_days SET status='submitted',seller_note=?,submitted_at=NOW(),updated_at=NOW() WHERE id=?")->execute([post('seller_note')?:null,$dayId]);db()->commit();}catch(Throwable $e){db()->rollBack();flash('error',$e->getMessage());redirect('/seller/orders/'.$d['order_id']);}log_event((int)$d['offer_id'],(int)$d['order_id'],'day.submitted',['day_no'=>(int)$d['day_no']]);flash('success','Tag '.$d['day_no'].' wurde eingereicht.');redirect('/seller/orders/'.$d['order_id']);
}

not_found();
