<?php
declare(strict_types=1);
require __DIR__.'/app/Core.php';

$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH) ?: '/';
$basePath=parse_url((string)app_config('app.url',''),PHP_URL_PATH) ?: '';
if ($basePath && $basePath!=='/' && str_starts_with($path,$basePath)) $path=substr($path,strlen($basePath)) ?: '/';
$method=$_SERVER['REQUEST_METHOD']??'GET';
if($method==='POST') csrf_verify();

function legal_page(string $title,string $intro,array $sections): never {
    ob_start(); ?><section class="legal"><div class="eyebrow">Information</div><h1><?=e($title)?></h1><p class="meta"><?=e($intro)?></p><?php foreach($sections as $h=>$p):?><h2><?=e($h)?></h2><p><?=e($p)?></p><?php endforeach;?></section><?php render($title,ob_get_clean()); exit;
}
function not_found(): never { http_response_code(404); render('Nicht gefunden','<div class="empty"><h1>404</h1><p>Die angeforderte Seite wurde nicht gefunden.</p></div>'); exit; }

if($path==='/'&&$method==='GET'){
 $offers=db()->query("SELECT o.*,c.name category_name FROM offers o JOIN categories c ON c.id=o.category_id WHERE o.status='active' ORDER BY o.created_at DESC LIMIT 6")->fetchAll();
 ob_start();?>
 <section class="hero"><div><div class="eyebrow">Diskrete Ankaufsplattform · 18+</div><h1>Du entscheidest, welche Aufträge zu dir passen.</h1><p>Konkrete Ankaufangebote, transparente Vergütung und ein geführter Ablauf von der Vorbereitung bis zur Auszahlung.</p><div class="actions"><a class="btn" href="<?=e(url('/angebote'))?>">Angebote entdecken</a><a class="btn secondary" href="<?=e(url('/registrieren'))?>">Als Verkäuferin registrieren</a></div></div><div class="panel"><h3>Kein klassischer Marktplatz</h3><p>Du musst keine Anzeigen erstellen und keine Käufer suchen. Der Betreiber veröffentlicht konkrete Aufträge.</p><div class="timeline"><div>✓ Keine öffentlichen Verkäuferprofile</div><div>✓ Anforderungen vor Annahme sichtbar</div><div>✓ Geschützte Nachweise</div><div>✓ Wallet & Auszahlung</div></div></div></section>
 <h2>Aktuelle Angebote</h2><div class="grid"><?php foreach($offers as $o):?><article class="card"><span class="badge"><?=e($o['category_name'])?></span><h3><?=e($o['title'])?></h3><p class="meta"><?=e(mb_strimwidth(strip_tags($o['description']),0,130,'…'))?></p><div class="price"><?=money($o['compensation'])?></div><a class="btn" href="<?=e(url('/angebot/'.$o['slug']))?>">Details</a></article><?php endforeach;?><?php if(!$offers):?><div class="empty">Aktuell sind noch keine Angebote veröffentlicht.</div><?php endif;?></div>
 <?php render('Startseite',ob_get_clean()); exit;
}
if($path==='/angebote'&&$method==='GET'){
 $q=trim((string)($_GET['q']??'')); $cat=(int)($_GET['category']??0);
 $sql="SELECT o.*,c.name category_name FROM offers o JOIN categories c ON c.id=o.category_id WHERE o.status='active'";$args=[];
 if($q!==''){$sql.=" AND (o.title LIKE ? OR o.description LIKE ?)";$args[]="%$q%";$args[]="%$q%";}
 if($cat){$sql.=" AND o.category_id=?";$args[]=$cat;}
 $sql.=" ORDER BY o.created_at DESC";$st=db()->prepare($sql);$st->execute($args);$offers=$st->fetchAll();
 $cats=db()->query("SELECT id,name FROM categories WHERE is_active=1 ORDER BY sort_order,name")->fetchAll();
 ob_start();?><div class="dashboard-head"><div><div class="eyebrow">Angebote</div><h1>Aktuelle Ankaufangebote</h1></div></div><form method="get" class="panel form-grid"><input name="q" value="<?=e($q)?>" placeholder="Angebote durchsuchen"><select name="category"><option value="">Alle Kategorien</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=$cat===$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select><button class="btn">Filtern</button></form><br><div class="grid"><?php foreach($offers as $o):?><article class="card"><span class="badge"><?=e($o['category_name'])?></span><h3><?=e($o['title'])?></h3><p class="meta"><?=e(mb_strimwidth(strip_tags($o['description']),0,150,'…'))?></p><div class="price"><?=money($o['compensation'])?></div><p class="meta"><?=$o['duration_days']?e($o['duration_days']).' Tage':'Individueller Umfang'?></p><a class="btn" href="<?=e(url('/angebot/'.$o['slug']))?>">Ansehen</a></article><?php endforeach;?><?php if(!$offers):?><div class="empty">Keine passenden Angebote gefunden.</div><?php endif;?></div><?php render('Angebote',ob_get_clean());exit;
}
if(preg_match('#^/angebot/([a-z0-9-]+)$#',$path,$m)&&$method==='GET'){
 $st=db()->prepare("SELECT o.*,c.name category_name FROM offers o JOIN categories c ON c.id=o.category_id WHERE o.slug=? AND o.status='active'");$st->execute([$m[1]]);$o=$st->fetch();if(!$o)not_found();
 ob_start();?><div class="eyebrow"><?=e($o['category_name'])?></div><h1><?=e($o['title'])?></h1><div class="grid two"><section class="panel"><h2>Das erwartet dich</h2><p><?=nl2br(e($o['description']))?></p><h3>Erfüllung</h3><p><?= $o['duration_days'] ? e($o['duration_days']).' Tage' : 'Individueller Umfang gemäß Angebot' ?></p></section><aside class="panel"><div class="meta">Vergütung</div><div class="price"><?=money($o['compensation'])?></div><p class="meta">Vor Annahme werden dir Vergütung, Dauer und die hinterlegten Anforderungen verbindlich angezeigt.</p><?php if(seller()):?><form method="post" action="<?=e(url('/angebot/'.$o['slug'].'/annehmen'))?>"><?=csrf_field()?><button class="btn">Angebot annehmen</button></form><?php else:?><a class="btn" href="<?=e(url('/login'))?>">Einloggen & annehmen</a><?php endif;?></aside></div><?php render($o['title'],ob_get_clean());exit;
}
if(preg_match('#^/angebot/([a-z0-9-]+)/annehmen$#',$path,$m)&&$method==='POST'){
 $s=require_seller(); if(!$s['email_verified_at']){flash('error','Bitte bestätige zuerst deine E-Mail-Adresse.');redirect('/dashboard');}
 $st=db()->prepare("SELECT * FROM offers WHERE slug=? AND status='active'");$st->execute([$m[1]]);$o=$st->fetch();if(!$o)not_found();
 $dupe=db()->prepare("SELECT COUNT(*) FROM orders x JOIN offers ox ON ox.id=x.offer_id WHERE x.seller_id=? AND ox.category_id=? AND x.status IN('precheck','running','shipping','review','payout')");
 $dupe->execute([$s['id'],$o['category_id']]); if((int)$dupe->fetchColumn()>0){flash('error','In dieser Kategorie besteht bereits ein aktiver Auftrag.');redirect('/angebote');}
 $no=order_number();
 db()->beginTransaction(); try{
   db()->prepare("INSERT INTO orders(order_no,seller_id,offer_id,offer_version,status,base_compensation,total_compensation,duration_days) VALUES(?,?,?,?, 'precheck',?,?,?)")->execute([$no,$s['id'],$o['id'],$o['current_version'],$o['compensation'],$o['compensation'],$o['duration_days']]);
   $oid=(int)db()->lastInsertId();
   db()->prepare("INSERT INTO order_runs(order_id,run_no,status) VALUES(?,1,'precheck')")->execute([$oid]);
   db()->prepare("INSERT INTO wallet_entries(seller_id,order_id,entry_type,amount,description) VALUES(?,?,'reserved',?,'Auftragswert vorgemerkt')")->execute([$s['id'],$oid,$o['compensation']]);
   db()->prepare("INSERT INTO system_events(seller_id,order_id,event_type,payload_json) VALUES(?,?,'order.accepted',?)")->execute([$s['id'],$oid,json_encode(['offer_version'=>$o['current_version']],JSON_UNESCAPED_UNICODE)]);
   db()->commit();
 }catch(Throwable $e){db()->rollBack();throw $e;}
 flash('success','Auftrag '.$no.' wurde angenommen. Bitte Vorabkontrolle durchführen.');redirect('/auftrag/'.$no);
}
if($path==='/registrieren'&&$method==='GET'){
 ob_start();?><div class="grid two"><section><div class="eyebrow">Verkäuferinnenkonto</div><h1>Registrieren</h1><p>Nur für Volljährige ab 18 Jahren. Es gibt kein öffentliches Verkäuferinnenprofil.</p></section><form class="panel" method="post"><?=csrf_field()?><div class="form-grid"><label>Vorname<input name="first_name" required></label><label>Nachname<input name="last_name" required></label><label>Geburtsdatum<input type="date" name="birth_date" required></label><label>Telefon<input name="phone" required></label><label>Straße / Hausnummer<input name="street" required></label><label>PLZ<input name="postal_code" required></label><label>Ort<input name="city" required></label><label>E-Mail<input type="email" name="email" required></label></div><label>Passwort<input type="password" name="password" minlength="10" required></label><label><input type="checkbox" name="adult" value="1" required style="width:auto"> Ich bestätige, dass ich mindestens 18 Jahre alt bin und die Plattformregeln akzeptiere.</label><button class="btn">Konto erstellen</button></form></div><?php render('Registrieren',ob_get_clean());exit;
}
if($path==='/registrieren'&&$method==='POST'){
 $birth=post('birth_date');$adult=($_POST['adult']??'')==='1';$email=strtolower(post('email'));$pass=(string)($_POST['password']??'');
 $age=$birth?date_diff(new DateTime($birth),new DateTime('today'))->y:0;
 if(!$adult||$age<18||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($pass)<10){flash('error','Bitte prüfe Volljährigkeit, E-Mail und Passwort.');redirect('/registrieren');}
 try{
  db()->prepare("INSERT INTO sellers(first_name,last_name,birth_date,street,postal_code,city,phone,email,password_hash) VALUES(?,?,?,?,?,?,?,?,?)")->execute([post('first_name'),post('last_name'),$birth,post('street'),post('postal_code'),post('city'),post('phone'),$email,password_hash($pass,PASSWORD_DEFAULT)]);
  $id=(int)db()->lastInsertId();[$raw,$hash]=make_token();db()->prepare("INSERT INTO email_verifications(seller_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 24 HOUR))")->execute([$id,$hash]);
  send_app_mail($email,'E-Mail bestätigen','<p>Bitte bestätige deine E-Mail:</p><p><a href="'.e(url('/email-bestaetigen?token='.$raw)).'">E-Mail bestätigen</a></p>');
  $_SESSION['seller_id']=$id;session_regenerate_id(true);flash('success','Konto erstellt. Bitte bestätige deine E-Mail-Adresse.');redirect('/dashboard');
 }catch(PDOException $e){flash('error','Diese E-Mail-Adresse ist bereits registriert.');redirect('/registrieren');}
}
if($path==='/email-bestaetigen'&&$method==='GET'){
 $hash=hash('sha256',(string)($_GET['token']??''));$st=db()->prepare("SELECT * FROM email_verifications WHERE token_hash=? AND expires_at>NOW()");$st->execute([$hash]);$v=$st->fetch();
 if($v){db()->prepare("UPDATE sellers SET email_verified_at=NOW() WHERE id=?")->execute([$v['seller_id']]);db()->prepare("DELETE FROM email_verifications WHERE seller_id=?")->execute([$v['seller_id']]);flash('success','E-Mail-Adresse erfolgreich bestätigt.');}else flash('error','Bestätigungslink ist ungültig oder abgelaufen.');
 redirect('/dashboard');
}
if($path==='/login'&&$method==='GET'){
 ob_start();?><div class="grid two"><section><div class="eyebrow">Verkäuferinnenbereich</div><h1>Willkommen zurück</h1><p>Melde dich an, um Aufträge, Nachweise, Wallet und Auszahlungen zu verwalten.</p></section><form class="panel" method="post"><?=csrf_field()?><label>E-Mail<input type="email" name="email" required></label><label>Passwort<input type="password" name="password" required></label><button class="btn">Anmelden</button><a href="<?=e(url('/passwort-vergessen'))?>">Passwort vergessen?</a></form></div><?php render('Login',ob_get_clean());exit;
}
if($path==='/login'&&$method==='POST'){
 $st=db()->prepare("SELECT * FROM sellers WHERE email=? AND deleted_at IS NULL");$st->execute([strtolower(post('email'))]);$s=$st->fetch();
 if(!$s||!password_verify((string)($_POST['password']??''),$s['password_hash'])){flash('error','E-Mail oder Passwort ist falsch.');redirect('/login');}
 session_regenerate_id(true);$_SESSION['seller_id']=$s['id'];redirect('/dashboard');
}
if($path==='/logout'){unset($_SESSION['seller_id']);session_regenerate_id(true);redirect('/');}
if($path==='/passwort-vergessen'&&$method==='GET'){
 ob_start();?><section class="legal"><h1>Passwort zurücksetzen</h1><form class="panel" method="post"><?=csrf_field()?><label>E-Mail<input type="email" name="email" required></label><button class="btn">Reset-Link anfordern</button></form></section><?php render('Passwort vergessen',ob_get_clean());exit;
}
if($path==='/passwort-vergessen'&&$method==='POST'){
 $st=db()->prepare("SELECT * FROM sellers WHERE email=? AND deleted_at IS NULL");$st->execute([strtolower(post('email'))]);$s=$st->fetch();
 if($s){[$raw,$hash]=make_token();db()->prepare("DELETE FROM password_resets WHERE seller_id=?")->execute([$s['id']]);db()->prepare("INSERT INTO password_resets(seller_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 30 MINUTE))")->execute([$s['id'],$hash]);send_app_mail($s['email'],'Passwort zurücksetzen','<p><a href="'.e(url('/passwort-reset?token='.$raw)).'">Neues Passwort setzen</a></p>');}
 flash('success','Wenn ein Konto vorhanden ist, wurde ein Reset-Link versendet.');redirect('/login');
}
if($path==='/passwort-reset'&&$method==='GET'){
 $token=(string)($_GET['token']??'');ob_start();?><section class="legal"><h1>Neues Passwort</h1><form class="panel" method="post"><?=csrf_field()?><input type="hidden" name="token" value="<?=e($token)?>"><label>Neues Passwort<input type="password" name="password" minlength="10" required></label><button class="btn">Passwort speichern</button></form></section><?php render('Passwort Reset',ob_get_clean());exit;
}
if($path==='/passwort-reset'&&$method==='POST'){
 $hash=hash('sha256',post('token'));$st=db()->prepare("SELECT * FROM password_resets WHERE token_hash=? AND expires_at>NOW() AND used_at IS NULL");$st->execute([$hash]);$r=$st->fetch();$p=(string)($_POST['password']??'');
 if(!$r||strlen($p)<10){flash('error','Reset-Link ungültig oder Passwort zu kurz.');redirect('/passwort-vergessen');}
 db()->prepare("UPDATE sellers SET password_hash=? WHERE id=?")->execute([password_hash($p,PASSWORD_DEFAULT),$r['seller_id']]);db()->prepare("UPDATE password_resets SET used_at=NOW() WHERE id=?")->execute([$r['id']]);flash('success','Passwort geändert.');redirect('/login');
}
if($path==='/dashboard'&&$method==='GET'){
 $s=require_seller();$st=db()->prepare("SELECT o.*,f.title FROM orders o JOIN offers f ON f.id=o.offer_id WHERE o.seller_id=? ORDER BY o.created_at DESC");$st->execute([$s['id']]);$orders=$st->fetchAll();
 $w=db()->prepare("SELECT entry_type,SUM(amount) total FROM wallet_entries WHERE seller_id=? GROUP BY entry_type");$w->execute([$s['id']]);$wallet=[];foreach($w->fetchAll() as $r)$wallet[$r['entry_type']]=$r['total'];
 ob_start();?><div class="dashboard-head"><div><div class="eyebrow">Heute</div><h1>Hallo <?=e($s['first_name'])?></h1><p class="meta"><?=$s['email_verified_at']?'E-Mail bestätigt':'E-Mail noch nicht bestätigt – Angebote können noch nicht angenommen werden.'?></p></div><a class="btn" href="<?=e(url('/angebote'))?>">Angebote entdecken</a></div><div class="grid"><div class="card"><div class="meta">Vorgemerkt</div><div class="stat"><?=money($wallet['reserved']??0)?></div></div><div class="card"><div class="meta">Verfügbar</div><div class="stat"><?=money($wallet['available']??0)?></div></div><div class="card"><div class="meta">Aktive Aufträge</div><div class="stat"><?=count(array_filter($orders,fn($o)=>!in_array($o['status'],['completed','rejected','archived'],true)))?></div></div></div><h2>Deine Aufträge</h2><div class="table-wrap"><table><thead><tr><th>Nr.</th><th>Auftrag</th><th>Status</th><th>Wert</th><th></th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><?=e($o['order_no'])?></td><td><?=e($o['title'])?></td><td><span class="badge"><?=e($o['status'])?></span></td><td><?=money($o['total_compensation'])?></td><td><a href="<?=e(url('/auftrag/'.$o['order_no']))?>">Öffnen</a></td></tr><?php endforeach;?></tbody></table></div><?php render('Dashboard',ob_get_clean());exit;
}
if(preg_match('#^/auftrag/(\d{8})$#',$path,$m)&&$method==='GET'){
 $s=require_seller();$st=db()->prepare("SELECT o.*,f.title,f.description,c.name category_name FROM orders o JOIN offers f ON f.id=o.offer_id JOIN categories c ON c.id=f.category_id WHERE o.order_no=? AND o.seller_id=?");$st->execute([$m[1],$s['id']]);$o=$st->fetch();if(!$o)not_found();
 $ev=db()->prepare("SELECT * FROM evidences WHERE order_id=? ORDER BY created_at DESC");$ev->execute([$o['id']]);$evidences=$ev->fetchAll();
 ob_start();?><div class="dashboard-head"><div><div class="eyebrow">Auftrag <?=e($o['order_no'])?></div><h1><?=e($o['title'])?></h1><span class="badge"><?=e($o['status'])?></span></div><div class="price"><?=money($o['total_compensation'])?></div></div><div class="grid two"><section class="panel"><h2>Ablauf</h2><div class="timeline"><div>1. Vorbereitung / Vorabkontrolle <?= $o['status']==='precheck'?'← aktuell':''?></div><div>2. Durchführung</div><div>3. Versand / digitale Abgabe</div><div>4. Prüfung</div><div>5. Auszahlung</div><div>6. Archiv</div></div></section><section class="panel"><h2>Vorabkontrolle</h2><?php if($o['status']==='precheck'):?><p>Lade die für den konkreten Artikel erforderlichen Startnachweise direkt über die Kamera hoch.</p><form method="post" action="<?=e(url('/auftrag/'.$o['order_no'].'/nachweis'))?>" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="type" value="precheck"><label>Kurze Artikelbezeichnung<input name="item_label" required placeholder="z. B. schwarze Sportsocken"></label><label>Pflichtfoto<input data-camera-input type="file" name="evidence" required></label><button class="btn">Nachweis einreichen</button></form><?php else:?><p class="meta">Die Vorabkontrolle ist abgeschlossen bzw. befindet sich nicht mehr in der Vorbereitungsphase.</p><?php endif;?></section></div><h2>Nachweise</h2><div class="table-wrap"><table><thead><tr><th>Typ</th><th>Zeitpunkt</th><th>Status</th></tr></thead><tbody><?php foreach($evidences as $evd):?><tr><td><?=e($evd['evidence_type'])?></td><td><?=e(date('d.m.Y H:i',strtotime($evd['created_at'])))?></td><td><?=e($evd['status'])?></td></tr><?php endforeach;?></tbody></table></div><?php render('Auftrag '.$o['order_no'],ob_get_clean());exit;
}
if(preg_match('#^/auftrag/(\d{8})/nachweis$#',$path,$m)&&$method==='POST'){
 $s=require_seller();$st=db()->prepare("SELECT * FROM orders WHERE order_no=? AND seller_id=?");$st->execute([$m[1],$s['id']]);$o=$st->fetch();if(!$o)not_found();
 try{$up=private_upload($_FILES['evidence']??[],'order-'.$o['id']);$run=db()->prepare("SELECT id FROM order_runs WHERE order_id=? ORDER BY run_no DESC LIMIT 1");$run->execute([$o['id']]);$runId=$run->fetchColumn()?:null;
  if(post('type')==='precheck'&&post('item_label')!==''){ $cnt=db()->prepare("SELECT COUNT(*) FROM order_items WHERE order_id=?");$cnt->execute([$o['id']]);if(!(int)$cnt->fetchColumn())db()->prepare("INSERT INTO order_items(order_id,order_run_id,label,locked_at) VALUES(?,?,?,NOW())")->execute([$o['id'],$runId,post('item_label')]);}
  db()->prepare("INSERT INTO evidences(order_id,order_run_id,seller_id,evidence_type,file_path,mime_type,file_size,sha256) VALUES(?,?,?,?,?,?,?,?)")->execute([$o['id'],$runId,$s['id'],post('type','precheck'),$up['path'],$up['mime'],$up['size'],$up['sha256']]);flash('success','Nachweis wurde sicher gespeichert.');
 }catch(Throwable $e){flash('error',$e->getMessage());}
 redirect('/auftrag/'.$o['order_no']);
}
if($path==='/admin/login'&&$method==='GET'){
 ob_start();?><section class="legal"><div class="eyebrow">Administration</div><h1>Admin-Login</h1><form method="post" class="panel"><?=csrf_field()?><label>E-Mail<input type="email" name="email" required></label><label>Passwort<input type="password" name="password" required></label><button class="btn">Anmelden</button></form></section><?php render('Admin Login',ob_get_clean());exit;
}
if($path==='/admin/login'&&$method==='POST'){
 $st=db()->prepare("SELECT * FROM admins WHERE email=?");$st->execute([strtolower(post('email'))]);$a=$st->fetch();if(!$a||!password_verify((string)($_POST['password']??''),$a['password_hash'])){flash('error','Login fehlgeschlagen.');redirect('/admin/login');}
 session_regenerate_id(true);$_SESSION['admin_id']=$a['id'];redirect('/admin');
}
if($path==='/admin/logout'){unset($_SESSION['admin_id']);session_regenerate_id(true);redirect('/admin/login');}
if($path==='/admin'&&$method==='GET'){
 require_admin();$counts=['offers'=>(int)db()->query("SELECT COUNT(*) FROM offers WHERE status='active'")->fetchColumn(),'sellers'=>(int)db()->query("SELECT COUNT(*) FROM sellers WHERE deleted_at IS NULL")->fetchColumn(),'orders'=>(int)db()->query("SELECT COUNT(*) FROM orders WHERE status NOT IN('completed','rejected','archived')")->fetchColumn(),'prechecks'=>(int)db()->query("SELECT COUNT(*) FROM evidences e JOIN orders o ON o.id=e.order_id WHERE e.evidence_type='precheck' AND e.status='submitted' AND o.status='precheck'")->fetchColumn()];
 ob_start();?><div class="dashboard-head"><div><div class="eyebrow">Administration</div><h1>Heute</h1></div><div class="actions"><a class="btn" href="<?=e(url('/admin/angebote'))?>">Angebote</a><a class="btn secondary" href="<?=e(url('/admin/kategorien'))?>">Kategorien</a><a class="btn secondary" href="<?=e(url('/admin/auftraege'))?>">Aufträge</a></div></div><div class="grid"><div class="card"><div class="meta">Aktive Angebote</div><div class="stat"><?=$counts['offers']?></div></div><div class="card"><div class="meta">Verkäuferinnen</div><div class="stat"><?=$counts['sellers']?></div></div><div class="card"><div class="meta">Aktive Aufträge</div><div class="stat"><?=$counts['orders']?></div></div></div><h2>Sofort bearbeiten</h2><div class="card"><strong><?=$counts['prechecks']?> offene Vorabnachweise</strong><p class="meta">Noch nicht geprüfte Vorabkontrollen priorisiert bearbeiten.</p><a href="<?=e(url('/admin/auftraege'))?>">Aufträge öffnen →</a></div><?php render('Admin Dashboard',ob_get_clean());exit;
}
if($path==='/admin/kategorien'&&$method==='GET'){
 require_admin();$cats=db()->query("SELECT * FROM categories ORDER BY sort_order,name")->fetchAll();ob_start();?><div class="dashboard-head"><div><div class="eyebrow">Administration</div><h1>Kategorien</h1></div></div><form method="post" class="panel form-grid"><?=csrf_field()?><input name="name" placeholder="Neue Kategorie" required><button class="btn">Kategorie anlegen</button></form><br><div class="table-wrap"><table><thead><tr><th>Name</th><th>System</th><th>Status</th></tr></thead><tbody><?php foreach($cats as $c):?><tr><td><?=e($c['name'])?></td><td><?=$c['is_system']?'Ja':'Nein'?></td><td><?=$c['is_active']?'Aktiv':'Deaktiviert'?></td></tr><?php endforeach;?></tbody></table></div><?php render('Kategorien',ob_get_clean());exit;
}
if($path==='/admin/kategorien'&&$method==='POST'){
 require_admin();$name=post('name');$slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',strtr($name,['ä'=>'ae','ö'=>'oe','ü'=>'ue','ß'=>'ss'])),'-'));db()->prepare("INSERT INTO categories(name,slug,is_system,is_active,sort_order) VALUES(?,?,0,1,999)")->execute([$name,$slug]);flash('success','Kategorie angelegt.');redirect('/admin/kategorien');
}
if($path==='/admin/angebote'&&$method==='GET'){
 require_admin();$offers=db()->query("SELECT o.*,c.name category_name FROM offers o JOIN categories c ON c.id=o.category_id ORDER BY o.created_at DESC")->fetchAll();$cats=db()->query("SELECT id,name FROM categories WHERE is_active=1 ORDER BY sort_order,name")->fetchAll();ob_start();?><div class="dashboard-head"><div><div class="eyebrow">Administration</div><h1>Angebote</h1></div></div><form method="post" class="panel"><?=csrf_field()?><div class="form-grid"><label>Titel<input name="title" required></label><label>Kategorie<select name="category_id"><?php foreach($cats as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select></label><label>Vergütung (€)<input type="number" step=".01" min="0" name="compensation" required></label><label>Dauer in Tagen<input type="number" min="1" name="duration_days"></label></div><label>Beschreibung<textarea name="description" required></textarea></label><label>Status<select name="status"><option value="draft">Entwurf</option><option value="active">Aktiv</option><option value="inactive">Deaktiviert</option></select></label><button class="btn">Angebot anlegen</button></form><br><div class="table-wrap"><table><thead><tr><th>Titel</th><th>Kategorie</th><th>Status</th><th>Vergütung</th></tr></thead><tbody><?php foreach($offers as $o):?><tr><td><?=e($o['title'])?></td><td><?=e($o['category_name'])?></td><td><?=e($o['status'])?></td><td><?=money($o['compensation'])?></td></tr><?php endforeach;?></tbody></table></div><?php render('Angebote verwalten',ob_get_clean());exit;
}
if($path==='/admin/angebote'&&$method==='POST'){
 require_admin();$title=post('title');$slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',strtr($title,['ä'=>'ae','ö'=>'oe','ü'=>'ue','ß'=>'ss'])),'-')).'-'.substr(bin2hex(random_bytes(3)),0,6);$comp=(float)post('compensation');$days=post('duration_days')!==''?(int)post('duration_days'):null;
 db()->beginTransaction();try{db()->prepare("INSERT INTO offers(category_id,title,slug,description,compensation,duration_days,fulfillment_type,status) VALUES(?,?,?,?,?,?,?,?)")->execute([(int)post('category_id'),$title,$slug,post('description'),$comp,$days,$days?'days':'one_time',post('status','draft')]);$id=(int)db()->lastInsertId();$snap=json_encode(['title'=>$title,'description'=>post('description'),'compensation'=>$comp,'duration_days'=>$days],JSON_UNESCAPED_UNICODE);db()->prepare("INSERT INTO offer_versions(offer_id,version_no,snapshot_json) VALUES(?,1,?)")->execute([$id,$snap]);db()->commit();}catch(Throwable $e){db()->rollBack();throw $e;}flash('success','Angebot angelegt.');redirect('/admin/angebote');
}
if($path==='/admin/auftraege'&&$method==='GET'){
 require_admin();$orders=db()->query("SELECT o.*,f.title,CONCAT(s.first_name,' ',s.last_name) seller_name FROM orders o JOIN offers f ON f.id=o.offer_id JOIN sellers s ON s.id=o.seller_id ORDER BY o.created_at DESC")->fetchAll();ob_start();?><div class="dashboard-head"><div><div class="eyebrow">Administration</div><h1>Aufträge</h1></div></div><div class="table-wrap"><table><thead><tr><th>Nr.</th><th>Verkäuferin</th><th>Auftrag</th><th>Status</th><th>Wert</th><th></th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><?=e($o['order_no'])?></td><td><?=e($o['seller_name'])?></td><td><?=e($o['title'])?></td><td><?=e($o['status'])?></td><td><?=money($o['total_compensation'])?></td><td><a href="<?=e(url('/admin/auftrag/'.$o['order_no']))?>">Prüfen</a></td></tr><?php endforeach;?></tbody></table></div><?php render('Aufträge',ob_get_clean());exit;
}
if(preg_match('#^/admin/auftrag/(\d{8})$#',$path,$m)&&$method==='GET'){
 require_admin();$st=db()->prepare("SELECT o.*,f.title,CONCAT(s.first_name,' ',s.last_name) seller_name,s.email FROM orders o JOIN offers f ON f.id=o.offer_id JOIN sellers s ON s.id=o.seller_id WHERE o.order_no=?");$st->execute([$m[1]]);$o=$st->fetch();if(!$o)not_found();$ev=db()->prepare("SELECT * FROM evidences WHERE order_id=? ORDER BY created_at");$ev->execute([$o['id']]);$evidences=$ev->fetchAll();
 ob_start();?><div class="dashboard-head"><div><div class="eyebrow">Auftrag <?=e($o['order_no'])?></div><h1><?=e($o['title'])?></h1><p class="meta"><?=e($o['seller_name'])?> · <?=e($o['email'])?></p></div><span class="badge"><?=e($o['status'])?></span></div><div class="panel"><h2>Nachweise</h2><?php foreach($evidences as $evd):?><div class="timeline"><div><strong><?=e($evd['evidence_type'])?></strong> · <?=e(date('d.m.Y H:i',strtotime($evd['created_at'])))?> · <?=e($evd['status'])?> <?php if($evd['status']==='submitted'):?><form method="post" action="<?=e(url('/admin/nachweis/'.$evd['id'].'/freigeben'))?>" style="display:inline"><?=csrf_field()?><button class="btn">Freigeben</button></form><?php endif;?></div></div><?php endforeach;?><?php if(!$evidences):?><p class="meta">Noch keine Nachweise.</p><?php endif;?></div><?php render('Auftrag '.$o['order_no'],ob_get_clean());exit;
}
if(preg_match('#^/admin/nachweis/(\d+)/freigeben$#',$path,$m)&&$method==='POST'){
 require_admin();$st=db()->prepare("SELECT e.*,o.order_no,o.id order_id FROM evidences e JOIN orders o ON o.id=e.order_id WHERE e.id=?");$st->execute([(int)$m[1]]);$ev=$st->fetch();if(!$ev)not_found();db()->prepare("UPDATE evidences SET status='accepted',reviewed_at=NOW() WHERE id=?")->execute([$ev['id']]);
 if($ev['evidence_type']==='precheck'){db()->prepare("UPDATE orders SET status='running',started_at=COALESCE(started_at,NOW()),updated_at=NOW() WHERE id=? AND status='precheck'")->execute([$ev['order_id']]);db()->prepare("UPDATE order_runs SET status='running',started_at=COALESCE(started_at,NOW()) WHERE order_id=? AND run_no=1")->execute([$ev['order_id']]);}
 flash('success','Nachweis freigegeben.');redirect('/admin/auftrag/'.$ev['order_no']);
}
if($path==='/so-funktioniert-es') legal_page('So funktioniert es','Vom Angebot bis zur Auszahlung – transparent und geführt.',['1. Registrieren'=>'Erstelle dein Verkäuferinnenkonto und bestätige deine E-Mail-Adresse.','2. Angebot auswählen'=>'Prüfe Vergütung, Dauer, Nachweise und Bedingungen vor der Annahme.','3. Vorabkontrolle'=>'Bei physischen Aufträgen wird der konkrete Artikel dokumentiert und vom Betreiber freigegeben.','4. Durchführung'=>'Dein Dashboard zeigt dir fällige Aufgaben und Nachweise.','5. Versand oder digitale Abgabe'=>'Je nach Auftrag folgt ein geführter Versand- oder Abgabeprozess.','6. Prüfung und Wallet'=>'Nach erfolgreichem Abschluss wird die freigegebene Vergütung verfügbar.']);
if($path==='/faq') legal_page('FAQ','Die wichtigsten Antworten zur Plattform.',['Wer kann sich registrieren?'=>'Ausschließlich volljährige Verkäuferinnen ab 18 Jahren.','Ist mein Profil öffentlich?'=>'Nein. Es gibt keine öffentlichen Verkäuferinnenprofile.','Wann startet ein Auftrag?'=>'Bei physischen Aufträgen nach vollständiger Freigabe der Vorabkontrolle.','Wann wird die Vergütung verfügbar?'=>'Nach vollständigem Abschluss und der vorgesehenen Prüfung.','Darf ich Artikel anderer Personen verwenden?'=>'Nein. Aufträge werden ausschließlich persönlich mit eigenen Artikeln bzw. eigenen Inhalten erfüllt.']);
if($path==='/regeln') legal_page('Plattform- und Auftragsregeln','Kurzfassung der zentralen Regeln. Die endgültigen Rechtstexte müssen vor Produktivbetrieb juristisch geprüft werden.',['Volljährigkeit'=>'Die Plattform ist ausschließlich für Personen ab 18 Jahren bestimmt.','Persönliche Erfüllung'=>'Aufträge, Artikel und digitale Inhalte müssen von der registrierten Verkäuferin selbst stammen bzw. persönlich erfüllt werden.','Nachweise'=>'Pflichtnachweise müssen fristgerecht und unverfälscht über die vorgesehenen Funktionen eingereicht werden.','Verstöße'=>'Nicht erfüllte Pflichten können geprüft und als Verstoß bestätigt oder verworfen werden.','Versand'=>'Es gelten die jeweiligen auftragsspezifischen Verpackungs- und Versandbedingungen.','Digitale Inhalte'=>'Digitale Inhalte müssen selbst erstellt sein; Rechtebedingungen werden beim konkreten Auftrag transparent vereinbart.']);
if($path==='/datenschutz') legal_page('Datenschutz','Entwurf – vor Produktivbetrieb mit den tatsächlich eingesetzten Diensten und Speicherfristen finalisieren.',['Verantwortlicher'=>'Die vollständigen Betreiberangaben werden im produktiven Rechtstext eingesetzt.','Verarbeitete Daten'=>'Registrierungs-, Vertrags-, Auftrags-, Nachweis-, Kommunikations- und Zahlungsdaten werden nur für definierte Plattformzwecke verarbeitet.','Private Dateien'=>'Nachweise werden außerhalb öffentlich erreichbarer Verzeichnisse gespeichert.','Betroffenenrechte'=>'Gesetzliche Auskunfts-, Berichtigungs-, Löschungs- und sonstige Betroffenenrechte bleiben unberührt.']);
if($path==='/impressum') legal_page('Impressum','Vor Produktivbetrieb mit den tatsächlichen Pflichtangaben des Betreibers vervollständigen.',['Anbieter'=>'Betreiberangaben noch einzusetzen.','Kontakt'=>'E-Mail-Adresse und weitere gesetzlich erforderliche Kontaktangaben noch einzusetzen.']);
if($path==='/kontakt') legal_page('Kontakt','Allgemeine Fragen können über die im Impressum angegebene Kontaktadresse gestellt werden.',['Auftragsfragen'=>'Für bestehende Aufträge soll der Auftragschat verwendet werden.','Sensible Dateien'=>'Bitte keine Nachweise per normaler E-Mail senden.']);
not_found();
