CREATE TABLE IF NOT EXISTS rate_limits (
 rate_key CHAR(64) PRIMARY KEY,
 hits INT UNSIGNED NOT NULL DEFAULT 0,
 window_started_at DATETIME NOT NULL,
 blocked_until DATETIME NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(blocked_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
