CREATE TABLE IF NOT EXISTS offer_templates (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(190) NOT NULL,
 snapshot_json LONGTEXT NOT NULL,
 active TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NULL,
 INDEX(active,name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
