CREATE TABLE IF NOT EXISTS system_outages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 starts_at DATETIME NOT NULL,
 ends_at DATETIME NOT NULL,
 duration_seconds INT UNSIGNED NOT NULL,
 reason TEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(starts_at,ends_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS outage_order_impacts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 outage_id BIGINT UNSIGNED NOT NULL,
 order_id BIGINT UNSIGNED NOT NULL,
 shifted_seconds INT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(outage_id,order_id),
 FOREIGN KEY(outage_id) REFERENCES system_outages(id) ON DELETE CASCADE,
 FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
