<?php
return [
    'driver'=>env('SESSION_DRIVER','database'),
    'lifetime'=>(int)env('SESSION_LIFETIME',120),
    'expire_on_close'=>false,
    'encrypt'=>filter_var(env('SESSION_ENCRYPT',true),FILTER_VALIDATE_BOOLEAN),
    'files'=>storage_path('framework/sessions'),
    'connection'=>env('SESSION_CONNECTION'),
    'table'=>'sessions',
    'store'=>env('SESSION_STORE'),
    'lottery'=>[2,100],
    'cookie'=>env('SESSION_COOKIE','wear_and_earn_session'),
    'path'=>'/',
    'domain'=>env('SESSION_DOMAIN'),
    'secure'=>filter_var(env('SESSION_SECURE_COOKIE',true),FILTER_VALIDATE_BOOLEAN),
    'http_only'=>true,
    'same_site'=>env('SESSION_SAME_SITE','lax'),
    'partitioned'=>false,
];
