@extends('layouts.app')
@section('title',$user->first_name.' '.$user->last_name)
@section('content')
<div class="page-head split"><div><span class="eyebrow">Benutzerakte #{{ $user->id }}</span><h1>{{ $user->first_name }} {{ $user->last_name }}</h1><p>{{ $user->email }}</p></div><span class="status {{ $user->status==='active'?'accepted':'rejected' }}">{{ strtoupper($user->status) }}</span></div>
<div class="admin-order-grid"><section>
<div class="panel"><h2>Stammdaten</h2><dl class="meta-list"><div><dt>Geburtsdatum</dt><dd>{{ $user->birth_date->format('d.m.Y') }}</dd></div><div><dt>Verifiziert</dt><dd>{{ $user->verified_at?->format('d.m.Y H:i') ?: 'Nein' }}</dd></div><div><dt>Telefon</dt><dd>{{ $user->profile?->phone ?: '–' }}</dd></div><div><dt>Adresse</dt><dd>{{ trim(($user->profile?->street??'').' '.($user->profile?->postal_code??'').' '.($user->profile?->city??'')) ?: '–' }}</dd></div></dl></div>
<div class="panel"><h2>Aufträge</h2><div class="table-card"><table><thead><tr><th>Nr.</th><th>Status</th><th>Vergütung</th></tr></thead><tbody>@foreach($user->orders->sortByDesc('created_at')->take(10) as $order)<tr><td><a href="{{ route('admin.orders.show',$order) }}">#{{ $order->order_number }}</a></td><td>{{ strtoupper($order->status) }}</td><td>{{ number_format($order->compensation_total,2,',','.') }} €</td></tr>@endforeach</tbody></table></div></div>
<div class="panel"><h2>Verwarnungen</h2>@forelse($user->warnings->sortByDesc('created_at') as $warning)<div style="padding:12px 0;border-bottom:1px solid var(--line)"><strong>{{ $warning->title }}</strong> · {{ strtoupper($warning->level) }}<p>{{ $warning->reason }}</p><small>{{ $warning->created_at->format('d.m.Y H:i') }}</small></div>@empty<p class="muted">Keine Verwarnungen.</p>@endforelse</div>
</section>
<aside>
<div class="panel"><h2>Verwarnung</h2><form method="post" action="{{ route('admin.users.warning',$user) }}" class="stack-form">@csrf<label>Stufe<select name="level"><option value="info">Hinweis</option><option value="warning">Verwarnung</option><option value="serious">Ernst</option></select></label><label>Titel<input name="title" required></label><label>Grund<textarea name="reason" rows="5" required></textarea></label><label>Gültig bis<input type="datetime-local" name="expires_at"></label><button class="btn secondary wide">Speichern</button></form></div>
<div class="panel"><h2>Einschränkung</h2><form method="post" action="{{ route('admin.users.restriction',$user) }}" class="stack-form">@csrf<label>Bereich<select name="type"><option value="offers">Neue Angebote / Auftragsstart</option><option value="payouts">Auszahlungen</option><option value="uploads">Uploads</option><option value="account">Gesamtes Konto</option></select></label><label>Grund<textarea name="reason" rows="4" required></textarea></label><label>Ende optional<input type="datetime-local" name="ends_at"></label><button class="btn primary wide">Einschränkung aktivieren</button></form></div>
<div class="panel"><h2>Aktive Einschränkungen</h2>@forelse($user->restrictions->where('active',true) as $item)<div class="notice"><strong>{{ strtoupper($item->type) }}</strong><p>{{ $item->reason }}</p><form method="post" action="{{ route('admin.users.restriction.remove',[$user,$item->id]) }}">@csrf<button class="btn secondary">Aufheben</button></form></div>@empty<p class="muted">Keine.</p>@endforelse</div>
</aside></div>
@endsection
