<?php
declare(strict_types=1);
// ADMIN ORDERS LIST/DETAIL
if ($path==='/admin/orders' && $method==='GET') {
    require_admin();$orders=db()->query("SELECT o.*,s.first_name,s.last_name FROM orders o JOIN sellers s ON s.id=o.seller_id ORDER BY FIELD(o.status,'running','precheck','completed','cancelled'),o.created_at DESC")->fetchAll();
    ob_start();?><div class="page-head"><div><span class="eyebrow">Aufträge</span><h1>Alle Aufträge</h1></div></div><div class="list"><?php foreach($orders as $o):?><a class="list-row" href="<?=e(url('/admin/order/'.$o['id']))?>"><div><strong><?=e($o['order_no'].' · '.$o['title_snapshot'])?></strong><span><?=e($o['first_name'].' '.$o['last_name'])?> · <?=e($o['successful_days'])?>/<?=e($o['required_success_days'])?> erfolgreich · +<?=e($o['extension_days'])?> Tag(e)</span></div><span class="status status-<?=e($o['status'])?>"><?=e(order_status_label($o['status']))?></span></a><?php endforeach;?><?php if(!$orders):?><div class="empty">Noch keine Aufträge vorhanden.</div><?php endif;?></div><?php render('Aufträge',ob_get_clean());exit;
}
if (preg_match('#^/admin/order/(\d+)$#',$path,$m) && $method==='GET') {
    require_admin();$id=(int)$m[1];$q=db()->prepare("SELECT o.*,s.first_name,s.last_name FROM orders o JOIN sellers s ON s.id=o.seller_id WHERE o.id=?");$q->execute([$id]);$o=$q->fetch();if(!$o)not_found();
    $q=db()->prepare('SELECT * FROM precheck_uploads WHERE order_id=? ORDER BY id');$q->execute([$id]);$pre=$q->fetchAll();$q=db()->prepare('SELECT * FROM order_days WHERE order_id=? ORDER BY day_no');$q->execute([$id]);$days=$q->fetchAll();
    ob_start();?><div class="page-head"><div><span class="eyebrow">Auftrag <?=e($o['order_no'])?></span><h1><?=e($o['title_snapshot'])?></h1><p><?=e($o['first_name'].' '.$o['last_name'])?> · <?=money($o['compensation'])?></p></div><span class="status status-<?=e($o['status'])?>"><?=e(order_status_label($o['status']))?></span></div><div class="stats compact"><div class="stat"><span>Erfolgreich</span><strong><?=e($o['successful_days'])?>/<?=e($o['required_success_days'])?></strong></div><div class="stat"><span>Verlängerung</span><strong>+<?=e($o['extension_days'])?></strong></div><div class="stat"><span>Fotos pro Tag</span><strong><?=e($o['daily_photo_count'])?></strong></div></div>
    <section class="panel"><h2>Vorabkontrolle</h2><p><?=nl2br(e($o['precheck_instructions']))?></p><p class="muted"><?=count($pre)?>/<?=e($o['precheck_photo_count'])?> Fotos vorhanden</p><?php if($pre):?><div class="photo-grid"><?php foreach($pre as $p):?><a href="<?=e(url('/file/precheck/'.$p['id']))?>" target="_blank"><img src="<?=e(url('/file/precheck/'.$p['id']))?>" alt="Vorabnachweis"></a><?php endforeach;?></div><?php endif;?><?php if($o['status']==='precheck'):?><form method="post" action="<?=e(url('/admin/order/'.$id.'/approve-precheck'))?>"><button class="btn" <?=count($pre)<(int)$o['precheck_photo_count']?'disabled':''?>>Vorabkontrolle freigeben & starten</button></form><?php endif;?></section>
    <?php if($days):?><section class="panel"><h2>Durchführungstage</h2><div class="day-list"><?php foreach($days as $d):$uq=db()->prepare('SELECT * FROM day_uploads WHERE day_id=? ORDER BY id');$uq->execute([$d['id']]);$ups=$uq->fetchAll();?><div class="day-row"><div class="day-main"><strong>Tag <?=e($d['day_no'])?><?=((int)$d['is_extension'])?' · Verlängerung':''?></strong><span class="status status-<?=e($d['status'])?>"><?=e(day_status_label($d['status']))?></span><?php if($d['seller_note']):?><p class="muted">Kommentar: <?=e($d['seller_note'])?></p><?php endif;?><div class="photo-grid small"><?php foreach($ups as $u):?><a href="<?=e(url('/file/day/'.$u['id']))?>" target="_blank"><img src="<?=e(url('/file/day/'.$u['id']))?>" alt="Tagesnachweis"></a><?php endforeach;?></div></div><?php if($d['status']==='submitted'):?><form class="review-actions" method="post" action="<?=e(url('/admin/day/'.$d['id'].'/review'))?>"><textarea name="admin_note" rows="2" placeholder="Notiz optional"></textarea><div><button class="btn" name="decision" value="fulfilled">✓ Erfüllt</button><button class="btn danger" name="decision" value="not_fulfilled">✕ Nicht erfüllt · +1 Tag</button></div></form><?php endif;?></div><?php endforeach;?></div></section><?php endif;?>
    <?php render('Auftrag '.$o['order_no'],ob_get_clean());exit;
}
if (preg_match('#^/admin/order/(\d+)/approve-precheck$#',$path,$m) && $method==='POST') {
    require_admin();$id=(int)$m[1];$q=db()->prepare('SELECT * FROM orders WHERE id=?');$q->execute([$id]);$o=$q->fetch();if(!$o)not_found();if($o['status']!=='precheck'){flash('error','Vorabkontrolle ist bereits abgeschlossen.');redirect('/admin/order/'.$id);} $c=db()->prepare('SELECT COUNT(*) FROM precheck_uploads WHERE order_id=?');$c->execute([$id]);if((int)$c->fetchColumn()<(int)$o['precheck_photo_count']){flash('error','Es fehlen Vorabfotos.');redirect('/admin/order/'.$id);}
    db()->beginTransaction();try{db()->prepare("UPDATE orders SET status='running',precheck_approved_at=NOW(),started_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$id]);$ins=db()->prepare("INSERT INTO order_days(order_id,day_no,is_extension,required_photo_count,status) VALUES(?,?,0,?,'planned')");for($d=1;$d<=(int)$o['required_success_days'];$d++)$ins->execute([$id,$d,$o['daily_photo_count']]);db()->commit();}catch(Throwable $e){db()->rollBack();throw $e;}log_event((int)$o['offer_id'],$id,'precheck.approved');sync_offer_status((int)$o['offer_id']);flash('success','Vorabkontrolle freigegeben. Auftrag läuft.');redirect('/admin/order/'.$id);
}
if (preg_match('#^/admin/day/(\d+)/review$#',$path,$m) && $method==='POST') {
    $a=require_admin();$dayId=(int)$m[1];$decision=post('decision');if(!in_array($decision,['fulfilled','not_fulfilled'],true)){flash('error','Ungültige Entscheidung.');redirect('/admin/orders');}
    $q=db()->prepare('SELECT d.*,o.offer_id,o.daily_photo_count,o.required_success_days FROM order_days d JOIN orders o ON o.id=d.order_id WHERE d.id=?');$q->execute([$dayId]);$d=$q->fetch();if(!$d)not_found();if($d['status']!=='submitted'){flash('error','Dieser Tag wurde bereits bewertet.');redirect('/admin/order/'.$d['order_id']);}
    db()->beginTransaction();try{db()->prepare('UPDATE order_days SET status=?,admin_note=?,reviewed_at=NOW(),reviewed_by=?,updated_at=NOW() WHERE id=?')->execute([$decision,post('admin_note')?:null,$a['id'],$dayId]);if($decision==='not_fulfilled'){$q=db()->prepare('SELECT id FROM order_days WHERE extension_for_day_id=?');$q->execute([$dayId]);if(!$q->fetchColumn()){$q=db()->prepare('SELECT COALESCE(MAX(day_no),0)+1 FROM order_days WHERE order_id=?');$q->execute([$d['order_id']]);$next=(int)$q->fetchColumn();db()->prepare("INSERT INTO order_days(order_id,day_no,is_extension,extension_for_day_id,required_photo_count,status) VALUES(?,?,1,?,?,'planned')")->execute([$d['order_id'],$next,$dayId,$d['daily_photo_count']]);db()->prepare('UPDATE orders SET extension_days=extension_days+1,updated_at=NOW() WHERE id=?')->execute([$d['order_id']]);}}db()->commit();}catch(Throwable $e){db()->rollBack();throw $e;}
    log_event((int)$d['offer_id'],(int)$d['order_id'],'day.reviewed',['day_id'=>$dayId,'decision'=>$decision]);sync_order_progress((int)$d['order_id']);flash('success',$decision==='fulfilled'?'Tag als erfüllt bestätigt.':'Tag nicht erfüllt: ein zusätzlicher Tag wurde angehängt.');redirect('/admin/order/'.$d['order_id']);
}

