@extends('layouts.app')
@section('title','Admin Auftrag #'.$order->order_number)
@section('content')
<div class="page-head split"><div><span class="eyebrow">Auftrag #{{ $order->order_number }}</span><h1>{{ data_get($order->offer_snapshot,'title') }}</h1><p>{{ $order->user->first_name }} {{ $order->user->last_name }} · {{ $order->user->email }}</p></div><div class="headline-amount"><span>Vergütung</span><strong>{{ number_format($order->compensation_total,2,',','.') }} €</strong></div></div>
<div class="admin-order-grid"><section><div class="panel"><div class="section-head"><div><span class="eyebrow">Prüfung</span><h2>Nachweise</h2></div></div>@forelse($order->days as $day)<div class="admin-day"><div><strong>Tag {{ $day->day_number }}</strong><small>{{ $day->date->format('d.m.Y') }} · {{ $day->proofs->count() }}/{{ $day->required_proofs }}</small></div><div class="proof-chips">@foreach($day->proofs as $proof)<a href="{{ route('admin.proofs.file',$proof) }}">{{ $proof->original_name }} · {{ $proof->review_status }}</a>@endforeach</div></div>@empty<p class="muted">Noch keine Auftragstage vorhanden.</p>@endforelse</div>
<div class="panel"><h2>Statushistorie</h2><div class="timeline">@foreach($order->statusHistory->sortByDesc('created_at') as $event)<div><span>{{ $event->created_at->format('d.m.Y H:i') }}</span><strong>{{ strtoupper(str_replace('_',' ',$event->to_status)) }}</strong><small>{{ $event->reason }}</small></div>@endforeach</div></div></section>
<aside><div class="panel"><h2>Status ändern</h2><form method="post" action="{{ route('admin.orders.status',$order) }}" class="stack-form">@csrf<label>Status<select name="status">@foreach(['precheck','approved','active','waiting_shipping','shipped','received','inspection','completed','cancelled','rejected','dispute'] as $status)<option value="{{ $status }}" @selected($order->status===$status)>{{ strtoupper(str_replace('_',' ',$status)) }}</option>@endforeach</select></label><label>Grund / Notiz<textarea name="reason" rows="4"></textarea></label><button class="btn secondary wide">Status speichern</button></form></div>
<div class="panel danger-zone"><h2>Vergütung</h2><p>Nach erfolgreicher Wareneingangs- und Abschlussprüfung wird die Vormerkung in verfügbares Guthaben umgebucht.</p><form method="post" action="{{ route('admin.orders.release',$order) }}">@csrf<button class="btn primary wide" @disabled($order->status==='compensation_released')>Vergütung freigeben</button></form></div></aside></div>
@endsection
