<?php
declare(strict_types=1);
$root=dirname(__DIR__);
if(is_file($root.'/config/app.php')){header('Location: ../');exit;}
$error=null;$success=false;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    $host=trim((string)($_POST['db_host']??'localhost'));$port=(int)($_POST['db_port']??3306);$name=trim((string)($_POST['db_name']??''));$user=trim((string)($_POST['db_user']??''));$pass=(string)($_POST['db_pass']??'');
    $appName=trim((string)($_POST['app_name']??'Auftragsportal'));$appUrl=rtrim(trim((string)($_POST['app_url']??'')),'/');
    $adminName=trim((string)($_POST['admin_name']??'Admin'));$adminEmail=strtolower(trim((string)($_POST['admin_email']??'')));$adminPass=(string)($_POST['admin_password']??'');
    $sellerFirst=trim((string)($_POST['seller_first_name']??''));$sellerLast=trim((string)($_POST['seller_last_name']??''));$sellerEmail=strtolower(trim((string)($_POST['seller_email']??'')));$sellerPass=(string)($_POST['seller_password']??'');
    try{
        if(!$name||!$user||!filter_var($adminEmail,FILTER_VALIDATE_EMAIL)||strlen($adminPass)<10)throw new RuntimeException('Datenbank sowie gültige Admin-Zugangsdaten sind Pflicht. Das Passwort muss mindestens 10 Zeichen haben.');
        if(!$appUrl||!filter_var($appUrl,FILTER_VALIDATE_URL))throw new RuntimeException('Bitte eine vollständige App-URL angeben, z. B. https://portal.example.de');
        if(($sellerEmail||$sellerFirst||$sellerLast||$sellerPass) && (!$sellerFirst||!$sellerLast||!filter_var($sellerEmail,FILTER_VALIDATE_EMAIL)||strlen($sellerPass)<10))throw new RuntimeException('Wenn du die erste Verkäuferin direkt anlegst, müssen alle vier Felder vollständig sein.');
        $pdo=new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
        $schema=file_get_contents($root.'/database/schema.sql');if($schema===false)throw new RuntimeException('Schema konnte nicht gelesen werden.');$pdo->exec($schema);
        $q=$pdo->prepare('SELECT COUNT(*) FROM admins');$q->execute();if((int)$q->fetchColumn()===0)$pdo->prepare('INSERT INTO admins(email,name,password_hash) VALUES(?,?,?)')->execute([$adminEmail,$adminName?:'Admin',password_hash($adminPass,PASSWORD_DEFAULT)]);
        if($sellerEmail){$q=$pdo->prepare('SELECT COUNT(*) FROM sellers WHERE email=?');$q->execute([$sellerEmail]);if((int)$q->fetchColumn()===0)$pdo->prepare('INSERT INTO sellers(email,first_name,last_name,password_hash) VALUES(?,?,?,?)')->execute([$sellerEmail,$sellerFirst,$sellerLast,password_hash($sellerPass,PASSWORD_DEFAULT)]);}
        $config="<?php\nreturn ".var_export(['app'=>['name'=>$appName?:'Auftragsportal','url'=>$appUrl,'timezone'=>'Europe/Berlin'],'db'=>['host'=>$host,'port'=>$port,'name'=>$name,'user'=>$user,'pass'=>$pass]],true).";\n";
        if(!is_dir($root.'/config')&&!mkdir($root.'/config',0770,true))throw new RuntimeException('Config-Ordner konnte nicht erstellt werden.');
        if(file_put_contents($root.'/config/app.php',$config,LOCK_EX)===false)throw new RuntimeException('config/app.php konnte nicht geschrieben werden.');
        $success=true;
    }catch(Throwable $e){$error=$e->getMessage();}
}
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Installation · Auftragsportal</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#111827;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{max-width:920px;margin:40px auto;padding:20px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:22px;padding:28px;box-shadow:0 18px 50px #1118270d}h1{font-size:34px;margin:0 0 8px}h2{font-size:18px;margin:28px 0 12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{display:block;font-weight:650;font-size:14px}input{width:100%;margin-top:7px;border:1px solid #d1d5db;border-radius:12px;padding:12px;font:inherit}.btn{border:0;background:#111827;color:#fff;border-radius:12px;padding:13px 18px;font-weight:750;cursor:pointer;margin-top:22px}.msg{padding:14px;border-radius:12px;margin:15px 0}.err{background:#fee2e2;color:#991b1b}.ok{background:#dcfce7;color:#166534}p{color:#6b7280;line-height:1.6}@media(max-width:700px){.grid{grid-template-columns:1fr}.wrap{margin:0;padding:12px}.card{border-radius:16px}}
</style></head><body><div class="wrap"><div class="card"><h1>Neue Installation</h1><p>Leere Datenbank verwenden. Es werden ausschließlich die Tabellen des neuen Auftragsportals angelegt.</p><?php if($error):?><div class="msg err"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($success):?><div class="msg ok"><strong>Installation abgeschlossen.</strong><br><a href="../">Zum Login</a></div><?php else:?><form method="post"><h2>Anwendung</h2><div class="grid"><label>Name<input name="app_name" value="Auftragsportal" required></label><label>URL<input type="url" name="app_url" placeholder="https://portal.example.de" required></label></div><h2>Datenbank</h2><div class="grid"><label>Host<input name="db_host" value="localhost" required></label><label>Port<input type="number" name="db_port" value="3306" required></label><label>Datenbank<input name="db_name" required></label><label>Benutzer<input name="db_user" required></label><label>Passwort<input type="password" name="db_pass"></label></div><h2>Admin / Käufer</h2><div class="grid"><label>Name<input name="admin_name" value="Admin" required></label><label>E-Mail<input type="email" name="admin_email" required></label><label>Passwort<input type="password" name="admin_password" minlength="10" required></label></div><h2>Erste Verkäuferin <small>(optional)</small></h2><div class="grid"><label>Vorname<input name="seller_first_name"></label><label>Nachname<input name="seller_last_name"></label><label>E-Mail<input type="email" name="seller_email"></label><label>Passwort<input type="password" name="seller_password" minlength="10"></label></div><button class="btn">Installation starten</button></form><?php endif;?></div></div></body></html>
