@extends('layouts.app')
@section('title','Kategorien')
@section('content')
<div class="page-head"><span class="eyebrow">Administration</span><h1>Kategorien & Produktmerkmale</h1><p>Vorgefertigte Kategorien bleiben bearbeitbar; neue Kategorien und Felder können ohne Codeänderung ergänzt werden.</p></div>
<div class="wallet-layout"><section>
@foreach($categories as $category)<article class="panel" style="margin-bottom:14px"><div class="day-top"><div><strong>{{ $category->icon }} {{ $category->name }}</strong><small>{{ $category->parent?->name ?: 'Hauptgruppe' }} · {{ strtoupper($category->kind) }} · {{ $category->offers_count }} Angebote</small></div><span class="status {{ $category->active?'accepted':'pending' }}">{{ $category->active?'AKTIV':'INAKTIV' }}</span></div>
<form method="post" action="{{ route('admin.categories.update',$category) }}" class="form-grid">@csrf @method('PUT')
<label>Name<input name="name" value="{{ $category->name }}" required></label><label>Icon<input name="icon" value="{{ $category->icon }}"></label><label>Elternkategorie<select name="parent_id"><option value="">– keine –</option>@foreach($parents as $parent)@if($parent->id!==$category->id)<option value="{{ $parent->id }}" @selected($category->parent_id===$parent->id)>{{ $parent->name }}</option>@endif @endforeach</select></label><label>Typ<select name="kind">@foreach(['group'=>'Gruppe','physical'=>'Physisch','digital'=>'Digital','special'=>'Sonderkategorie'] as $key=>$label)<option value="{{ $key }}" @selected($category->kind===$key)>{{ $label }}</option>@endforeach</select></label><label>Sortierung<input type="number" min="0" name="sort_order" value="{{ $category->sort_order }}"></label><label class="check"><input type="checkbox" name="active" value="1" @checked($category->active)><span>Aktiv</span></label><div class="full"><button class="btn secondary">Kategorie speichern</button></div>
</form>
@if($category->kind!=='group')<details style="margin-top:12px"><summary><strong>Produktmerkmale ({{ $category->fields->count() }})</strong></summary>
@foreach($category->fields as $field)<form method="post" action="{{ route('admin.categories.fields.update',[$category,$field->id]) }}" class="option-editor-row" style="margin-top:10px">@csrf @method('PUT')<label>Name<input name="label" value="{{ $field->label }}"></label><label>Typ<select name="type">@foreach(['text','textarea','number','select','multiselect','boolean','date'] as $type)<option value="{{ $type }}" @selected($field->type===$type)>{{ $type }}</option>@endforeach</select></label><label>Optionen<textarea name="options_text" rows="2">{{ is_array($field->options)?implode("\n",$field->options):'' }}</textarea></label><label>Sortierung<input type="number" name="sort_order" value="{{ $field->sort_order }}"></label><label class="check"><input type="checkbox" name="required" value="1" @checked($field->required)><span>Pflicht</span></label><label class="check"><input type="checkbox" name="active" value="1" @checked($field->active)><span>Aktiv</span></label><button class="btn secondary">Speichern</button></form>@endforeach
<form method="post" action="{{ route('admin.categories.fields.store',$category) }}" class="form-grid" style="margin-top:14px">@csrf<label>Neues Feld<input name="label" required></label><label>Typ<select name="type">@foreach(['text','textarea','number','select','multiselect','boolean','date'] as $type)<option value="{{ $type }}">{{ $type }}</option>@endforeach</select></label><label class="full">Optionen – eine pro Zeile<textarea name="options_text" rows="2"></textarea></label><label class="check"><input type="checkbox" name="required" value="1"><span>Pflichtfeld</span></label><div><button class="btn primary">Feld hinzufügen</button></div></form>
</details>@endif
@if(!$category->offers()->whereHas('orders')->exists() && !$category->children()->exists())<form method="post" action="{{ route('admin.categories.destroy',$category) }}" style="margin-top:12px" onsubmit="return confirm('Kategorie wirklich löschen?')">@csrf @method('DELETE')<button class="btn secondary">Kategorie löschen</button></form>@endif
</article>@endforeach
</section>
<aside class="panel"><h2>Neue Kategorie</h2><form method="post" action="{{ route('admin.categories.store') }}" class="stack-form">@csrf<label>Name<input name="name" required></label><label>Icon<input name="icon"></label><label>Elternkategorie<select name="parent_id"><option value="">– keine –</option>@foreach($parents as $parent)<option value="{{ $parent->id }}">{{ $parent->name }}</option>@endforeach</select></label><label>Typ<select name="kind"><option value="physical">Physisch</option><option value="digital">Digital</option><option value="special">Sonderkategorie</option><option value="group">Gruppe</option></select></label><label>Sortierung<input type="number" name="sort_order" value="0" min="0"></label><label class="check"><input type="checkbox" name="active" value="1" checked><span>Aktiv</span></label><button class="btn primary wide">Kategorie anlegen</button></form></aside>
</div>
@endsection
